"""
Formatting

recipe Name: (item type, is craftable, resources, anvilTier)

resources -> [(resource name, quantity needed, resource type, has recipe), ...]
"""

RECIPES = {
	'Boxing Gloves': ('weapon', True, [('Crimson String', 1, 'material', False), ('Cue Tape', 5, 'material', False)], 1),
	'Wooden Spear': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Copper Bar', 10, 'mining', False)], 1),
	'Wooden Bow': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Thread', 30, 'material', False)], 1),
	'Gnarled Wand': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Oak Logs', 30, 'choppin', False)], 1),
	'Farmer Brim': ('armor', True, [('Spore Cap', 5, 'material', False), ('Copper Ore', 15, 'mining', False)], 1),
	'Orange Tee': ('armor', True, [('Spore Cap', 10, 'material', False), ('Oak Logs', 15, 'choppin', False)], 1),
	'Torn Jeans': ('armor', True, [('Frog Leg', 20, 'material', False), ('Copper Bar', 8, 'mining', False), ('Thread', 15, 'material', False)], 1),
	'Flip Flops': ('armor', True, [('Bean Slices', 30, 'material', False), ('Copper Bar', 20, 'mining', False), ('Grass Leaf', 20, 'choppin', False)], 1),
	'Copper Pickaxe': ('tool', True, [('Copper Bar', 20, 'mining', False), ('Frog Leg', 50, 'material', False)], 1),
	'Cramped Mining Pouch': ('bag', True, [('Copper Ore', 120, 'mining', False)], 1),
	'Copper Chopper': ('tool', True, [('Copper Bar', 20, 'mining', False), ('Oak Logs', 30, 'choppin', False), ('Thread', 30, 'material', False)], 1),
	'Cramped Choppin Pouch': ('bag', True, [('Oak Logs', 150, 'choppin', False), ('Trusty Nails', 30, 'material', False)], 1),
	'Leather Cap': ('armor', True, [('Frog Leg', 25, 'material', False), ('Oak Logs', 75, 'choppin', False), ('Thread', 25, 'material', False)], 1),
	'The Stingers': ('weapon', True, [('Copper Bar', 30, 'mining', False), ('Oak Logs', 100, 'choppin', False), ('Trusty Nails', 50, 'material', False)], 1),
	'Cramped Food Pouch': ('bag', True, [('Nomwich', 75, 'food', False), ('Hot Dog', 25, 'food', False), ('Oak Logs', 75, 'choppin', False), ('Copper Bar', 20, 'mining', False)], 1),
	'Cramped Material Pouch': ('bag', True, [('Trusty Nails', 125, 'material', False), ('Frog Leg', 50, 'material', False), ('Bean Slices', 50, 'material', False)], 1),
	'Copper Helmet': ('armor', True, [('Copper Bar', 75, 'mining', False), ('Bean Slices', 75, 'material', False)], 1),
	'Copper Platebody': ('armor', True, [('Copper Bar', 90, 'mining', False), ('Trusty Nails', 150, 'material', False)], 1),
	'Copper Platelegs': ('armor', True, [('Copper Bar', 110, 'mining', False), ('Bleach Logs', 200, 'choppin', False)], 1),
	'Copper Boots': ('armor', True, [('Copper Bar', 200, 'mining', False)], 1),
	'Militia Helm': ('armor', True, [('Iron Bar', 35, 'mining', False), ('Copper Ore', 300, 'mining', False), ('Copper Helmet', 2, 'armor', True)], 1),
	'Thief Hood': ('armor', True, [('Iron Bar', 35, 'mining', False), ('Thread', 300, 'material', False), ('Copper Helmet', 2, 'armor', True)], 1),
	'Top Hat': ('armor', True, [('Iron Bar', 35, 'mining', False), ('Oak Logs', 550, 'choppin', False), ('Copper Helmet', 2, 'armor', True)], 1),
	'Party Hat': ('armor', False, [('Iron Bar', 200, 'mining', False), ('Copper Helmet', 4, 'armor', True)], 1),
	'Steel Axe': ('weapon', True, [('Slime Sludge', 300, 'material', False), ('Boring Brick', 200, 'material', False)], 1),
	'Birch Longbow': ('weapon', True, [('Slime Sludge', 300, 'material', False), ('Bleach Logs', 400, 'choppin', False)], 1),
	'Quarterstaff': ('weapon', True, [('Slime Sludge', 300, 'material', False), ('Copper Bar', 175, 'mining', False)], 1),
	'Copper Band': ('armor', True, [('Copper Bar', 300, 'mining', False)], 1),
	'Iron Pickaxe': ('tool', True, [('Iron Bar', 175, 'mining', False), ('Carrot Cube', 300, 'material', False)], 1),
	'Small Mining Pouch': ('bag', True, [('Iron Ore', 850, 'mining', False)], 1),
	'Iron Hatchet': ('tool', True, [('Jungle Logs', 450, 'choppin', False), ('Boring Brick', 250, 'material', False)], 1),
	'Small Choppin Pouch': ('bag', True, [('Bleach Logs', 850, 'choppin', False)], 1),
	'Iron Helmet': ('armor', True, [('Iron Bar', 225, 'mining', False), ('Goblin Ear', 400, 'material', False)], 1),
	'Iron Platebody': ('armor', True, [('Iron Bar', 275, 'mining', False), ('Jungle Logs', 800, 'choppin', False)], 1),
	'Iron Platelegs': ('armor', True, [('Iron Bar', 300, 'mining', False), ('Boring Brick', 300, 'material', False)], 1),
	'Anvil Tab 2': ('misc', False, [('Iron Bar', 500, 'mining', False), ('Chain Link', 200, 'material', False), ('Forest Fibres', 400, 'choppin', False), ('Bullfrog Horn', 250, 'material', False)], 1),
	'Blue Tee': ('armor', True, [('Spore Cap', 25, 'material', False), ('Oak Logs', 50, 'choppin', False), ('Orange Tee', 2, 'armor', True)], 1),
	'Sleek Shank': ('armor', True, [('Thread', 300, 'material', False), ('Wooden Spear', 3, 'weapon', True), ('Wooden Bow', 3, 'weapon', True), ('Gnarled Wand', 3, 'weapon', True)], 1),
	'Iron Boots': ('armor', True, [('Trusty Nails', 500, 'material', False), ('Iron Bar', 125, 'mining', False), ('Copper Boots', 2, 'armor', True)], 1),
	'Steel Band': ('armor', True, [('Iron Bar', 600, 'mining', False)], 1),
	'Purple Tupacband': ('armor', True, [('Bleach Logs', 150, 'choppin', False), ('Iron Ore', 75, 'mining', False), ('Crude Oil', 100, 'mining', False)], 1),
	'Icing Ironbite': ('food', True, [('Iron Ore', 5, 'mining', False), ('Small Mana Potion', 2, 'food', False)], 1),
	'Saucy Logfries': ('food', True, [('Jungle Logs', 6, 'choppin', False), ('Small Life Potion', 3, 'food', False)], 1),
	'Goo Galoshes': ('armor', True, [('Slime Sludge', 600, 'material', False), ('Jungle Logs', 1000, 'choppin', False), ('Copper Boots', 2, 'armor', True)], 1),
	'Fur Shirt': ('armor', True, [('Goblin Ear', 500, 'material', False), ('Iron Bar', 500, 'mining', False)], 1),
	'Hide Shirt': ('armor', True, [('Bleach Logs', 325, 'choppin', False), ('Copper Platebody', 2, 'armor', True), ('Steel Axe', 1, 'weapon', True)], 1),
	'Eco Friendly Oil': ('mining', True, [('Crude Oil', 1, 'mining', False), ('Grass Leaf', 1, 'choppin', False)], 1),
	'Dooble Goopi': ('armor', True, [('Slime Sludge', 1000, 'material', False), ('Copper Band', 1, 'armor', True), ('Steel Band', 1, 'armor', True)], 1),
	'Bleached Designer Wode Patch Pants': ('armor', True, [('Torn Jeans', 10, 'armor', True), ('Plank', 400, 'material', False), ('Bleach Logs', 900, 'choppin', False)], 1),
	'Dirty Coal Miner Baggy Soot Pants': ('armor', True, [('Torn Jeans', 8, 'armor', True), ('Iron Ore', 250, 'mining', False)], 1),
	'Peanut': ('food', True, [('Hot Dog', 2, 'food', False), ('Copper Ore', 1, 'mining', False), ('Bleach Logs', 1, 'choppin', False)], 1),
	'Golden Peanut': ('food', True, [('Peanut', 100, 'food', True), ('Gold Bar', 50, 'mining', False)], 1),
	'Blunderbag': ('bag', True, [('Spore Tee', 2, 'armor', False), ('Dank Paypay Chest', 1, 'bag', False), ('Spore Cap', 169, 'material', False)], 1),
	'Purple Tee': ('armor', True, [('Red Spore Cap', 40, 'material', False), ('Bleach Logs', 100, 'choppin', False), ('Orange Tee', 3, 'armor', True)], 1),
	'Green Tee': ('armor', True, [('Thread', 150, 'material', False), ('Spore Tee', 2, 'armor', False), ('Orange Tee', 3, 'armor', True)], 1),
	'Black Tee': ('armor', True, [('Orange Tee', 5, 'armor', True), ('Blue Tee', 3, 'armor', True), ('Purple Tee', 3, 'armor', True), ('Green Tee', 3, 'armor', True)], 1),
	'Blunderhills NPC Completion Token': ('misc', False, [('Easy Blunderhills NPC Token', 1, 'misc', True), ('Med Blunderhills NPC Token', 1, 'misc', True), ('Hard Blunderhills NPC Token', 1, 'misc', True)], 1),
	'Blunder Skills Completion Token': ('misc', False, [('Platinum Bar', 1000, 'mining', False), ('Veiny Logs', 2000, 'choppin', False), ('Amarok Helmet', 1, 'armor', True)], 1),
	'Blunderhills Misc Completion Token': ('misc', False, [('Golden Peanut', 30, 'food', True), ('Golden Plop', 12, 'material', False), ('Bolt Cutters', 1, 'bag', False), ('Carrot Launcher', 2, 'weapon', False)], 1),
	'Easy Blunderhills NPC Token': ('misc', False, [('Woodsman Token', 1, 'misc', False), ('Glumlee Token', 1, 'misc', False), ('Stiltzcho Token', 1, 'misc', False), ('Funguy Token', 1, 'misc', False)], 1),
	'Med Blunderhills NPC Token': ('misc', False, [('Krunk Token', 1, 'misc', False), ('Tiki Chief Token', 1, 'misc', False), ('Dog Bone Token', 1, 'misc', False), ('Papua Piggea Token', 1, 'misc', False)], 1),
	'Hard Blunderhills NPC Token': ('misc', False, [('Picnic Token', 1, 'misc', False), ('TP Pete Token', 1, 'misc', False), ('Sproutinald Token', 1, 'misc', False), ('Dazey Token', 1, 'misc', False)], 1),
	'Amarok Helmet': ('armor', True, [('Amarok Slab', 20, 'inf', False), ('Forest Fibres', 3000, 'choppin', False), ('Woodular Circle', 8, 'material', False)], 1),
	'Amarok Bodyplate': ('armor', True, [('Amarok Slab', 10, 'inf', False), ('Iron Bar', 500, 'mining', False), ('Corn Kernels', 1200, 'material', False)], 1),
	'Amarok Hinds': ('armor', True, [('Amarok Slab', 6, 'inf', False), ('Chain Link', 500, 'material', False), ('Bullfrog Horn', 1000, 'material', False)], 1),
	'Amarok Paws': ('armor', True, [('Amarok Slab', 5, 'inf', False), ('Grass Leaf', 250, 'choppin', False), ('Iron Boots', 1, 'armor', True)], 1),
	'Chaotic Amarok Pendant': ('armor', True, [('Chaotic Amarok Slab', 4, 'inf', False), ('Amarok Slab', 10, 'inf', False), ('Distilled Water', 25, 'material', False)], 1),
	'Copper Fish Rod': ('tool', True, [('Copper Bar', 200, 'mining', False), ('Goldfish', 400, 'fish', False)], 1),
	'Cramped Fish Pouch': ('bag', True, [('Goldfish', 180, 'fish', False)], 1),
	'Copper Netted Net': ('tool', True, [('Jungle Logs', 500, 'choppin', False), ('Fly', 400, 'bug', False)], 1),
	'Cramped Bug Pouch': ('bag', True, [('Fly', 180, 'bug', False)], 1),
	'Iron Fishing Rod': ('tool', True, [('Iron Bar', 300, 'mining', False), ('Hermit Can', 850, 'fish', False), ('Distilled Water', 3, 'material', False)], 1),
	'Small Fish Pouch': ('bag', True, [('Hermit Can', 425, 'fish', False), ('Distilled Water', 2, 'material', False)], 1),
	'Reinforced Net': ('tool', True, [('Forest Fibres', 800, 'choppin', False), ('Butterfly', 850, 'bug', False), ('Distilled Water', 3, 'material', False)], 1),
	'Small Bug Pouch': ('bag', True, [('Butterfly', 425, 'bug', False), ('Distilled Water', 2, 'material', False)], 1),
	'Gold Helmet': ('armor', True, [('Fly', 2000, 'bug', False), ('Copper Helmet', 4, 'armor', True), ('Gold Bar', 250, 'mining', False)], 2),
	'Gold Platebody': ('armor', True, [('Pocket Sand', 1500, 'material', False), ('Copper Platebody', 5, 'armor', True), ('Gold Bar', 350, 'mining', False)], 2),
	'Gold Platelegs': ('armor', True, [('Goldfish', 500, 'fish', False), ('Copper Platelegs', 6, 'armor', True), ('Gold Bar', 475, 'mining', False)], 2),
	'Gold Boots': ('armor', True, [('Gold Bar', 600, 'mining', False), ('Iron Boots', 2, 'armor', True), ('Distilled Water', 8, 'material', False)], 2),
	'Bandage Wraps': ('weapon', True, [('Cue Tape', 5000, 'material', False), ('The Stingers', 10, 'weapon', True), ('Potty Rolls', 2000, 'choppin', False)], 2),
	'Royal Bayonet': ('weapon', True, [('Forest Fibres', 1250, 'choppin', False), ('Steel Axe', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)], 2),
	'Spiked Menace': ('weapon', True, [('Gold Bar', 250, 'mining', False), ('Birch Longbow', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)], 2),
	'Starlight': ('weapon', True, [('Chain Link', 1000, 'material', False), ('Quarterstaff', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)], 2),
	'Gold Pickaxe': ('tool', True, [('Megalodon Tooth', 2500, 'material', False), ('Gold Bar', 800, 'mining', False), ('Iron Pickaxe', 5, 'tool', True)], 2),
	'Average Mining Pouch': ('bag', True, [('Cramped Mining Pouch', 10, 'bag', True), ('Small Mining Pouch', 4, 'bag', True), ('Gold Ore', 1400, 'mining', False)], 2),
	'Golden Axe': ('tool', True, [('Golden Dubloon', 5, 'inf', False), ('Crabby Cakey', 2000, 'material', False), ('Iron Hatchet', 5, 'tool', True)], 2),
	'Average Choppin Pouch': ('bag', True, [('Cramped Choppin Pouch', 10, 'bag', True), ('Small Choppin Pouch', 5, 'bag', True), ('Forest Fibres', 1800, 'choppin', False)], 2),
	'Gold Fishing Rod': ('tool', True, [('Hermit Can', 2500, 'fish', False), ('Leather Hide', 1000, 'material', False), ('Iron Fishing Rod', 5, 'tool', True)], 2),
	'Average Fish Pouch': ('bag', True, [('Cramped Fish Pouch', 10, 'bag', True), ('Small Fish Pouch', 5, 'bag', True), ('Hermit Can', 1500, 'fish', False)], 2),
	'Gilded Net': ('tool', True, [('Golden Dubloon', 5, 'inf', False), ('Butterfly', 2500, 'bug', False), ('Reinforced Net', 5, 'tool', True)], 2),
	'Average Bug Pouch': ('bag', True, [('Cramped Bug Pouch', 10, 'bag', True), ('Small Bug Pouch', 5, 'bag', True), ('Butterfly', 1600, 'bug', False)], 2),
	'Defenders Dignity': ('armor', True, [('Goldfish', 16000, 'fish', False), ('Golden Plop', 17, 'material', False), ('Distilled Water', 15, 'material', False)], 2),
	'Strung Bludgeon': ('armor', True, [('Bullfrog Horn', 9000, 'material', False), ('Glass Shard', 10, 'material', False), ('Distilled Water', 20, 'material', False)], 2),
	'Average Food Pouch': ('bag', True, [('Cramped Food Pouch', 10, 'bag', True), ('Meat Pie', 250, 'food', False), ('Icing Ironbite', 600, 'food', True), ('Saucy Logfries', 600, 'food', True)], 2),
	'Average Material Pouch': ('bag', True, [('Cramped Material Pouch', 10, 'bag', True), ('Glass Shard', 1, 'material', False), ('Chain Link', 1250, 'material', False)], 2),
	'Platinum Helmet': ('armor', True, [('Jellyfish', 4000, 'fish', False), ('Iron Helmet', 4, 'armor', True), ('Platinum Bar', 750, 'mining', False)], 2),
	'Platinum Platbody': ('armor', True, [('Potato Remains', 5000, 'material', False), ('Iron Platebody', 5, 'armor', True), ('Platinum Bar', 1000, 'mining', False)], 2),
	'Platinum Shins': ('armor', True, [('Sentient Cereal', 500, 'bug', False), ('Iron Platelegs', 6, 'armor', True), ('Platinum Bar', 1250, 'mining', False)], 2),
	'Platinum Boots': ('armor', True, [('Tropilogs', 8000, 'choppin', False), ('Jellyfish', 8000, 'fish', False), ('Gold Boots', 3, 'armor', True)], 2),
	'Bullet': ('food', True, [('Forest Fibres', 10, 'choppin', False), ('Fly', 10, 'bug', False)], 2),
	'Enforced Slasher': ('weapon', True, [('Nuget Cake', 8, 'material', False), ('Leather Hide', 9000, 'material', False), ('Royal Bayonet', 2, 'weapon', True)], 2),
	'Pharoah Bow': ('weapon', True, [('Woodular Circle', 8, 'material', False), ('Bloach', 5200, 'fish', False), ('Spiked Menace', 2, 'weapon', True)], 2),
	'Crows Nest': ('weapon', True, [('Golden Plop', 8, 'material', False), ('Fruitfly', 8500, 'bug', False), ('Starlight', 2, 'weapon', True)], 2),
	'Platinum Pickaxe': ('tool', True, [('Platinum Bar', 1000, 'mining', False), ('Pincer Arm', 10500, 'material', False), ('Gold Pickaxe', 3, 'tool', True)], 2),
	'Sizable Mining Pouch': ('bag', True, [('Platinum Ore', 6750, 'mining', False), ('Average Mining Pouch', 5, 'bag', True)], 2),
	'Plat Hatchet': ('tool', True, [('Tropilogs', 8000, 'choppin', False), ('Chain Link', 6000, 'material', False), ('Golden Axe', 3, 'tool', True)], 2),
	'Sizable Choppin Pouch': ('bag', True, [('Tropilogs', 6750, 'choppin', False), ('Average Choppin Pouch', 5, 'bag', True)], 2),
	'Plat Fishing Rod': ('tool', True, [('Bloach', 12000, 'fish', False), ('Platinum Bar', 2000, 'mining', False), ('Gold Fishing Rod', 3, 'tool', True)], 2),
	'Sizable Fish Pouch': ('bag', True, [('Bloach', 6750, 'fish', False), ('Average Fish Pouch', 5, 'bag', True)], 2),
	'Platinet': ('tool', True, [('Fruitfly', 8000, 'bug', False), ('Platinum Ore', 6000, 'mining', False), ('Gilded Net', 3, 'tool', True)], 2),
	'Sizable Bug Pouch': ('bag', True, [('Fruitfly', 6750, 'bug', False), ('Average Bug Pouch', 5, 'bag', True)], 2),
	'Sizable Food Pouch': ('bag', True, [('Golden Meat Pie', 9, 'food', False), ('Nuget Cake', 6, 'material', False), ('Average Food Pouch', 2, 'bag', True)], 2),
	'Sizable Materials Pouch': ('bag', True, [('Golden Plop', 5, 'material', False), ('Woodular Circle', 5, 'material', False), ('Average Material Pouch', 2, 'bag', True)], 2),
	'Anvil Tab 3': ('misc', False, [('Platinum Bar', 2000, 'mining', False), ('Not Yet', 2000, '', False), ('Fruitfly', 2000, 'bug', False), ('High Steaks', 1500, 'material', False)], 2),
	'Empty Box': ('misc', True, [('Hermit Can', 250, 'fish', False), ('Megalodon Tooth', 400, 'material', False), ('Distilled Water', 4, 'material', False)], 2),
	'Googley Eyes': ('misc', True, [('Woodular Circle', 2, 'material', False), ('Distilled Water', 5, 'material', False)], 2),
	'FMJ Bullet': ('food', True, [('Gold Ore', 15, 'mining', False), ('Bullet', 2, 'food', True)], 2),
	'Viking Cap': ('armor', True, [('Militia Helm', 5, 'armor', True), ('Gold Bar', 400, 'mining', False), ('Glass Shard', 2, 'material', False)], 2),
	'Sleek Coif': ('armor', True, [('Thief Hood', 5, 'armor', True), ('Tropilogs', 2000, 'choppin', False), ('Glass Shard', 2, 'material', False)], 2),
	'Witch Hat': ('armor', True, [('Top Hat', 5, 'armor', True), ('Corn Kernels', 4000, 'material', False), ('Glass Shard', 2, 'material', False)], 2),
	'Studded Hide': ('armor', True, [('Hide Shirt', 4, 'armor', True), ('Megalodon Tooth', 4000, 'material', False), ('Nuget Cake', 1, 'material', False)], 2),
	'Feral Leathering': ('armor', True, [('Fur Shirt', 4, 'armor', True), ('Stick', 3000, 'material', False), ('Nuget Cake', 1, 'material', False)], 2),
	'Furled Robes': ('armor', True, [('Tattered Cloth', 4, 'armor', False), ('Leather Hide', 1500, 'material', False), ('Nuget Cake', 1, 'material', False)], 2),
	'Cavern Trekkers': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Copper Ore', 1500, 'mining', False), ('Iron Ore', 1200, 'mining', False)], 2),
	'Angler Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Goldfish', 1250, 'fish', False), ('Hermit Can', 1000, 'fish', False)], 2),
	'Logger Heels': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Jungle Logs', 1600, 'choppin', False), ('Forest Fibres', 1000, 'choppin', False)], 2),
	'Bandito Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Fly', 2000, 'bug', False), ('Butterfly', 1250, 'bug', False)], 2),
	'Slurpin Herm': ('food', True, [('Hermit Can', 5, 'fish', False), ('Average Strength Potion', 2, 'food', False)], 2),
	'Buttered Toasted Butter': ('food', True, [('Butterfly', 5, 'bug', False), ('Kebab Sticks', 1, 'food', False)], 2),
	'Dootjat Eye': ('misc', True, [('Silver Antique', 1, 'inf', False), ('Gold Bar', 80, 'mining', False), ('Ghost', 1, 'material', False)], 2),
	'Sandy Satchel': ('bag', True, [('Golden Plop', 1, 'material', False), ('Snakeskinventory Bag', 1, 'bag', False), ('Pocket Sand', 777, 'material', False)], 2),
	'Efaunt Helmet': ('armor', True, [('Ripped Tunic', 20, 'inf', False), ('Trimmed Rune Platelegs', 1, 'armor', False), ('Armor Upgrade Stone C', 2, 'inf', False), ('Dootjat Eye', 3, 'misc', True)], 2),
	'Efaunt Ribcage': ('armor', True, [('Ripped Tunic', 10, 'inf', False), ('Midnight Cookie', 10, 'food', False), ('Distilled Water', 25, 'material', False)], 2),
	'Efaunt Hipilium': ('armor', True, [('Ripped Tunic', 7, 'inf', False), ('Minuteglass', 3, 'material', False), ('Distilled Water', 25, 'material', False)], 2),
	'Efaunts Broken Ankles': ('armor', True, [('Ripped Tunic', 5, 'inf', False), ('Nuget Cake', 3, 'material', False), ('Platinum Boots', 1, 'armor', True)], 2),
	'Efaunt Trunculus': ('armor', True, [('Ribbed Tunic', 4, 'material', False), ('Ripped Tunic', 15, 'inf', False), ('Bandage Wraps', 1, 'weapon', True), ('Pharoah Bow', 1, 'weapon', True)], 2),
}


MATERIALS = {
    'World 1': {
        'Anvil': ['Thread', 'Trusty Nails', 'Boring Brick', 'Chain Link', 'Leather Hide'],
        'Boss': ['Amarok Slab', 'Chaotic Amarok Slab'],
        'Chopping': ['Oak Logs', 'Grass Leaf', 'Bleach Logs', 'Jungle Logs', 'Forest Fibres', 'Potty Rolls'],
        'Foods': ['Nomwich', 'Hot Dog', 'Golden Meat Pie'],
        'Mining': ['Crude Oil', 'Copper Ore', 'Copper Bar', 'Iron Ore', 'Iron Bar', 'Gold Ore', 'Gold Bar', 'Platinum Ore', 'Platinum Bar'],
        'Monster Drops': ['Spore Cap', 'Frog Leg', 'Bean Slices', 'Slime Sludge', 'Carrot Cube', 'Red Spore Cap', 'Goblin Ear', 'Plank', 'Bullfrog Horn', 'Stick', 'Corn Kernels'],
        'Other': ['Crimson String', 'Cue Tape', 'Tattered Cloth', 'Silver Antique'],
        'Potions': ['Small Life Potion', 'Small Mana Potion', 'Average Strength Potion'],
        "Tokens": ['Glumlee Token', 'Picnic Token', 'Woodsman Token', 'Stiltzcho Token', 'Krunk Token',  'TP Pete Token',  'Funguy Token', 'Dazey Token', 'Tiki Chief Token', 'Sproutinald Token', 'Dog Bone Token', 'Papua Piggea Token',],
        'Unique Drops': ['Spore Tee', 'Dank Paypay Chest', 'Snakeskinventory Bag', 'Carrot Launcher', 'Woodular Circle', 'Golden Plop']
    },
    'World 2': {
        'Catching': ['Fly', 'Butterfly', 'Sentient Cereal', 'Fruitfly'],
        'Chopping': ['Tropilogs'],
        'Fishing': ['Goldfish', 'Hermit Can', 'Jellyfish', 'Bloach'],
        'Foods': ['Kebab Sticks', 'Meat Pie'],
        'Monster Drops': ['Pocket Sand', 'Megalodon Tooth', 'Crabby Cakey', 'Pincer Arm', 'Potato Remains', 'High Steaks',],
        'Other': ['Golden Dubloon', 'Distilled Water'],
        'Unique Drops': ['Glass Shard', 'Nuget Cake', 'Ghost']
    }
}

MATERIAL_WEIGHTS = [
    ('Thread', 'Trusty Nails', 'Oak Logs', 'Nomwich', 'Hot Dog', 'Crude Oil', 'Copper Ore', 'Spore Cap', 'Frog Leg', 'Crimson String', 'Cue Tape'),
    ('Boring Brick', 'Grass Leaf', 'Bleach Logs', 'Copper Bar', 'Iron Ore', 'Bean Slices', 'Slime Sludge', 'Small Life Potion', 'Small Mana Potion', 'Spore Tee', 'Dank Paypay Chest'),
    ('Chain Link', 'Jungle Logs', 'Iron Bar', 'Carrot Cube', 'Goblin Ear', 'Stick', 'Snakeskinventory Bag'),
    ('Leather Hide', 'Forest Fibres', 'Gold Ore', 'Plank', 'Bullfrog Horn', 'Tattered Cloth', 'Average Strength Potion',  'Fly', 'Goldfish', 'Kebab Sticks', 'Bolt Cutters'),
    ('Gold Bar', 'Red Spore Cap', 'Silver Antique', 'Woodular Circle', 'Butterfly', 'Hermit Can', 'Meat Pie'),
    ('Potty Rolls', 'Corn Kernels', 'Sentient Cereal', 'Jellyfish', 'Golden Dubloon', 'Veiny Logs'),
    ('Amarok Slab', 'Tropilogs', 'Bloach', 'Pocket Sand', 'Distilled Water', 'Carrot Launcher'),
    ('Golden Meat Pie', 'Platinum Ore', 'Golden Plop', 'Fruitfly', 'Megalodon Tooth'),
    ('Platinum Bar', 'Crabby Cakey', 'Glass Shard', 'Ripped Tunic'),
    ('Pincer Arm', 'Nuget Cake', 'Minuteglass','Armor Upgrade Stone C'),
    ('Potato Remains', 'High Steaks', 'Ghost'),
    ('Trimmed Rune Platelegs'),
    ('Midnight Cookie'),
    ('Chaotic Amarok Slab'),
    ('Ribbed Tunic')
]