"""
Formatting

recipe Name: (item type, is craftable, resources, anvilTier)

resources -> [(resource name, quantity needed, resource type, has recipe), ...]
"""

RECIPES = {
	'Boxing Gloves': ('weapon', True, [('Crimson String', 1, 'material', False), ('Cue Tape', 5, 'material', False)], 1),
	'Wooden Spear': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Copper Bar', 10, 'mining', False)], 1),
	'Wooden Bow': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Thread', 30, 'material', False)], 1),
	'Gnarled Wand': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Oak Logs', 30, 'choppin', False)], 1),
	'Farmer Brim': ('armor', True, [('Spore Cap', 5, 'material', False), ('Copper Ore', 15, 'mining', False)], 1),
	'Orange Tee': ('armor', True, [('Spore Cap', 10, 'material', False), ('Oak Logs', 15, 'choppin', False)], 1),
	'Torn Jeans': ('armor', True, [('Frog Leg', 20, 'material', False), ('Copper Bar', 8, 'mining', False), ('Thread', 15, 'material', False)], 1),
	'Flip Flops': ('armor', True, [('Bean Slices', 30, 'material', False), ('Copper Bar', 20, 'mining', False), ('Grass Leaf', 20, 'choppin', False)], 1),
	'Copper Pickaxe': ('tool', True, [('Copper Bar', 13, 'mining', False), ('Frog Leg', 30, 'material', False)], 1),
	'Cramped Mining Pouch': ('bag', True, [('Copper Ore', 120, 'mining', False)], 1),
	'Copper Chopper': ('tool', True, [('Copper Bar', 13, 'mining', False), ('Oak Logs', 30, 'choppin', False), ('Thread', 15, 'material', False)], 1),
	'Cramped Choppin Pouch': ('bag', True, [('Oak Logs', 150, 'choppin', False), ('Trusty Nails', 30, 'material', False)], 1),
	'Leather Cap': ('armor', True, [('Frog Leg', 25, 'material', False), ('Oak Logs', 45, 'choppin', False), ('Thread', 13, 'material', False)], 1),
	'The Stingers': ('weapon', True, [('Copper Bar', 20, 'mining', False), ('Oak Logs', 75, 'choppin', False), ('Trusty Nails', 20, 'material', False)], 1),
	'Cramped Food Pouch': ('bag', True, [('Nomwich', 75, 'food', False), ('Hot Dog', 25, 'food', False), ('Oak Logs', 60, 'choppin', False), ('Copper Bar', 15, 'mining', False)], 1),
	'Cramped Material Pouch': ('bag', True, [('Trusty Nails', 80, 'material', False), ('Frog Leg', 40, 'material', False), ('Bean Slices', 30, 'material', False)], 1),
	'Copper Helmet': ('armor', True, [('Copper Bar', 30, 'mining', False), ('Bean Slices', 50, 'material', False)], 1),
	'Copper Platebody': ('armor', True, [('Copper Bar', 45, 'mining', False), ('Trusty Nails', 120, 'material', False)], 1),
	'Copper Platelegs': ('armor', True, [('Copper Bar', 60, 'mining', False), ('Bleach Logs', 150, 'choppin', False)], 1),
	'Copper Boots': ('armor', True, [('Copper Bar', 125, 'mining', False)], 1),
	'Militia Helm': ('armor', True, [('Iron Bar', 25, 'mining', False), ('Copper Ore', 150, 'mining', False), ('Copper Helmet', 2, 'armor', True)], 1),
	'Thief Hood': ('armor', True, [('Iron Bar', 25, 'mining', False), ('Thread', 150, 'material', False), ('Copper Helmet', 2, 'armor', True)], 1),
	'Top Hat': ('armor', True, [('Iron Bar', 25, 'mining', False), ('Oak Logs', 200, 'choppin', False), ('Copper Helmet', 2, 'armor', True)], 1),
	'Party Hat': ('armor', False, [('Iron Bar', 200, 'mining', False), ('Copper Helmet', 4, 'armor', True)], 1),
	'Steel Axe': ('weapon', True, [('Slime Sludge', 125, 'material', False), ('Boring Brick', 125, 'material', False)], 1),
	'Birch Longbow': ('weapon', True, [('Slime Sludge', 125, 'material', False), ('Bleach Logs', 250, 'choppin', False)], 1),
	'Quarterstaff': ('weapon', True, [('Slime Sludge', 125, 'material', False), ('Copper Bar', 100, 'mining', False)], 1),
	'Copper Band': ('armor', True, [('Copper Bar', 300, 'mining', False)], 1),
	'Iron Pickaxe': ('tool', True, [('Iron Bar', 100, 'mining', False), ('Carrot Cube', 200, 'material', False)], 1),
	'Small Mining Pouch': ('bag', True, [('Iron Ore', 700, 'mining', False)], 1),
	'Iron Hatchet': ('tool', True, [('Jungle Logs', 250, 'choppin', False), ('Boring Brick', 125, 'material', False)], 1),
	'Small Choppin Pouch': ('bag', True, [('Bleach Logs', 800, 'choppin', False)], 1),
	'Iron Helmet': ('armor', True, [('Iron Bar', 125, 'mining', False), ('Goblin Ear', 300, 'material', False)], 1),
	'Iron Platebody': ('armor', True, [('Iron Bar', 150, 'mining', False), ('Jungle Logs', 600, 'choppin', False)], 1),
	'Iron Platelegs': ('armor', True, [('Iron Bar', 170, 'mining', False), ('Boring Brick', 225, 'material', False)], 1),
	'Anvil Tab 2': ('token', False, [('Iron Bar', 250, 'mining', False), ('Chain Link', 200, 'material', False), ('Forest Fibres', 400, 'choppin', False), ('Bullfrog Horn', 250, 'material', False)], 1),
	'Blue Tee': ('armor', True, [('Spore Cap', 25, 'material', False), ('Oak Logs', 50, 'choppin', False), ('Orange Tee', 2, 'armor', True)], 1),
	'Sleek Shank': ('armor', True, [('Thread', 300, 'material', False), ('Wooden Spear', 3, 'weapon', True), ('Wooden Bow', 3, 'weapon', True), ('Gnarled Wand', 3, 'weapon', True)], 1),
	'Iron Boots': ('armor', True, [('Trusty Nails', 500, 'material', False), ('Iron Bar', 125, 'mining', False), ('Copper Boots', 2, 'armor', True)], 1),
	'Steel Band': ('armor', True, [('Iron Bar', 600, 'mining', False)], 1),
	'Purple Tupacband': ('armor', True, [('Bleach Logs', 100, 'choppin', False), ('Iron Ore', 50, 'mining', False), ('Crude Oil', 60, 'mining', False)], 1),
	'Icing Ironbite': ('food', True, [('Iron Ore', 5, 'mining', False), ('Small Mana Potion', 2, 'food', False)], 1),
	'Saucy Logfries': ('food', True, [('Jungle Logs', 6, 'choppin', False), ('Small Life Potion', 3, 'food', False)], 1),
	'Goo Galoshes': ('armor', True, [('Slime Sludge', 600, 'material', False), ('Jungle Logs', 1000, 'choppin', False), ('Copper Boots', 2, 'armor', True)], 1),
	'Fur Shirt': ('armor', True, [('Goblin Ear', 500, 'material', False), ('Iron Bar', 500, 'mining', False)], 1),
	'Hide Shirt': ('armor', True, [('Bleach Logs', 325, 'choppin', False), ('Copper Platebody', 2, 'armor', True), ('Steel Axe', 1, 'weapon', True)], 1),
	'Eco Friendly Oil': ('mining', True, [('Crude Oil', 1, 'mining', False), ('Grass Leaf', 1, 'choppin', False)], 1),
	'Dooble Goopi': ('armor', True, [('Slime Sludge', 1000, 'material', False), ('Copper Band', 1, 'armor', True), ('Steel Band', 1, 'armor', True)], 1),
	'Bleached Designer Wode Patch Pants': ('armor', True, [('Torn Jeans', 10, 'armor', True), ('Plank', 275, 'material', False), ('Bleach Logs', 700, 'choppin', False)], 1),
	'Dirty Coal Miner Baggy Soot Pants': ('armor', True, [('Torn Jeans', 8, 'armor', True), ('Iron Ore', 200, 'mining', False)], 1),
	'Peanut': ('food', True, [('Hot Dog', 2, 'food', False), ('Copper Ore', 1, 'mining', False), ('Bleach Logs', 1, 'choppin', False)], 1),
	'Golden Peanut': ('food', True, [('Peanut', 100, 'food', True), ('Gold Bar', 50, 'mining', False)], 1),
	'Blunderbag': ('bag', True, [('Spore Tee', 2, 'armor', False), ('Dank Paypay Chest', 1, 'bag', False), ('Spore Cap', 169, 'material', False)], 1),
	'Purple Tee': ('armor', True, [('Red Spore Cap', 40, 'material', False), ('Bleach Logs', 100, 'choppin', False), ('Orange Tee', 3, 'armor', True)], 1),
	'Green Tee': ('armor', True, [('Thread', 150, 'material', False), ('Spore Tee', 2, 'armor', False), ('Orange Tee', 3, 'armor', True)], 1),
	'Black Tee': ('armor', True, [('Orange Tee', 5, 'armor', True), ('Blue Tee', 3, 'armor', True), ('Purple Tee', 3, 'armor', True), ('Green Tee', 3, 'armor', True)], 1),
	'Blunderhills NPC Completion Token': ('token', False, [('Easy Blunderhills NPC Token', 1, 'token', True), ('Med Blunderhills NPC Token', 1, 'token', True), ('Hard Blunderhills NPC Token', 1, 'token', True)], 1),
	'Blunder Skills Completion Token': ('token', False, [('Platinum Bar', 1000, 'mining', False), ('Veiny Logs', 2000, 'choppin', False), ('Amarok Helmet', 1, 'armor', True)], 1),
	'Blunderhills Misc Completion Token': ('token', False, [('Golden Peanut', 30, 'food', True), ('Golden Plop', 12, 'material', False), ('Bolt Cutters', 1, 'bag', False), ('Carrot Launcher', 2, 'weapon', False)], 1),
	'Easy Blunderhills NPC Token': ('token', False, [('Woodsman Token', 1, 'token', False), ('Glumlee Token', 1, 'token', False), ('Stiltzcho Token', 1, 'token', False), ('Funguy Token', 1, 'token', False)], 1),
	'Med Blunderhills NPC Token': ('token', False, [('Krunk Token', 1, 'token', False), ('Tiki Chief Token', 1, 'token', False), ('Dog Bone Token', 1, 'token', False), ('Papua Piggea Token', 1, 'token', False)], 1),
	'Hard Blunderhills NPC Token': ('token', False, [('Picnic Token', 1, 'token', False), ('TP Pete Token', 1, 'token', False), ('Sproutinald Token', 1, 'token', False), ('Dazey Token', 1, 'token', False)], 1),
	'Amarok Helmet': ('armor', True, [('Amarok Slab', 20, 'material', False), ('Forest Fibres', 2500, 'choppin', False), ('Woodular Circle', 8, 'material', False)], 1),
	'Amarok Bodyplate': ('armor', True, [('Amarok Slab', 10, 'material', False), ('Iron Bar', 400, 'mining', False), ('Corn Kernels', 900, 'material', False)], 1),
	'Amarok Hinds': ('armor', True, [('Amarok Slab', 6, 'material', False), ('Chain Link', 400, 'material', False), ('Bullfrog Horn', 700, 'material', False)], 1),
	'Amarok Paws': ('armor', True, [('Amarok Slab', 5, 'material', False), ('Grass Leaf', 125, 'choppin', False), ('Iron Boots', 1, 'armor', True)], 1),
	'Fishing Overalls': ('armor', True, [('Bleached Designer Wode Patch Pants', 3, 'armor', True), ('Goldfish', 500, 'fish', False)], 1),
	'Bandito Pantaloon': ('armor', True, [('Dirty Coal Miner Baggy Soot Pants', 3, 'armor', True), ('Fly', 500, 'bug', False)], 1),
	'Chaotic Amarok Pendant': ('armor', True, [('Chaotic Amarok Slab', 4, 'material', False), ('Amarok Slab', 10, 'material', False), ('Distilled Water', 25, 'material', False)], 1),
	'Copper Fish Rod': ('tool', True, [('Copper Bar', 200, 'mining', False), ('Goldfish', 400, 'fish', False)], 1),
	'Cramped Fish Pouch': ('bag', True, [('Goldfish', 180, 'fish', False)], 1),
	'Copper Netted Net': ('tool', True, [('Jungle Logs', 500, 'choppin', False), ('Fly', 400, 'bug', False)], 1),
	'Cramped Bug Pouch': ('bag', True, [('Fly', 180, 'bug', False)], 1),
	'Iron Fishing Rod': ('tool', True, [('Iron Bar', 300, 'mining', False), ('Hermit Can', 850, 'fish', False), ('Distilled Water', 3, 'material', False)], 1),
	'Small Fish Pouch': ('bag', True, [('Hermit Can', 425, 'fish', False), ('Distilled Water', 2, 'material', False)], 1),
	'Reinforced Net': ('tool', True, [('Forest Fibres', 800, 'choppin', False), ('Butterfly', 850, 'bug', False), ('Distilled Water', 3, 'material', False)], 1),
	'Small Bug Pouch': ('bag', True, [('Butterfly', 425, 'bug', False), ('Distilled Water', 2, 'material', False)], 1),
	'Silkskin Traps': ('tool', True, [('Poison Froge', 1, 'critter', False), ('Redox Salts', 5, 'material', False)], 1),
	'Small Critter Pouch': ('bag', True, [('Froge', 200, 'critter', False), ('Redox Salts', 3, 'material', False)], 1),
	'Ceramic Skull': ('tool', True, [('Forest Soul', 250, 'soul', False), ('Redox Salts', 5, 'material', False)], 1),
	'Small Soul Pouch': ('bag', True, [('Forest Soul', 200, 'soul', False), ('Redox Salts', 3, 'material', False)], 1),
	'Gold Helmet': ('armor', True, [('Fly', 2000, 'bug', False), ('Copper Helmet', 4, 'armor', True), ('Gold Bar', 250, 'mining', False)], 2),
	'Gold Platebody': ('armor', True, [('Pocket Sand', 1500, 'material', False), ('Copper Platebody', 5, 'armor', True), ('Gold Bar', 350, 'mining', False)], 2),
	'Gold Platelegs': ('armor', True, [('Goldfish', 500, 'fish', False), ('Copper Platelegs', 6, 'armor', True), ('Gold Bar', 475, 'mining', False)], 2),
	'Gold Boots': ('armor', True, [('Gold Bar', 600, 'mining', False), ('Iron Boots', 2, 'armor', True), ('Distilled Water', 4, 'material', False)], 2),
	'Bandage Wraps': ('weapon', True, [('Cue Tape', 5000, 'material', False), ('The Stingers', 5, 'weapon', True), ('Potty Rolls', 2000, 'choppin', False)], 2),
	'Royal Bayonet': ('weapon', True, [('Forest Fibres', 1250, 'choppin', False), ('Steel Axe', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)], 2),
	'Spiked Menace': ('weapon', True, [('Gold Bar', 250, 'mining', False), ('Birch Longbow', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)], 2),
	'Starlight': ('weapon', True, [('Chain Link', 1000, 'material', False), ('Quarterstaff', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)], 2),
	'Gold Pickaxe': ('tool', True, [('Megalodon Tooth', 2500, 'material', False), ('Gold Bar', 800, 'mining', False), ('Iron Pickaxe', 3, 'tool', True)], 2),
	'Average Mining Pouch': ('bag', True, [('Cramped Mining Pouch', 5, 'bag', True), ('Small Mining Pouch', 3, 'bag', True), ('Gold Ore', 1400, 'mining', False)], 2),
	'Golden Axe': ('tool', True, [('Golden Dubloon', 5, 'material', False), ('Crabby Cakey', 2000, 'material', False), ('Iron Hatchet', 3, 'tool', True)], 2),
	'Average Choppin Pouch': ('bag', True, [('Cramped Choppin Pouch', 5, 'bag', True), ('Small Choppin Pouch', 3, 'bag', True), ('Forest Fibres', 1800, 'choppin', False)], 2),
	'Gold Fishing Rod': ('tool', True, [('Hermit Can', 2500, 'fish', False), ('Leather Hide', 1000, 'material', False), ('Iron Fishing Rod', 3, 'tool', True)], 2),
	'Average Fish Pouch': ('bag', True, [('Cramped Fish Pouch', 5, 'bag', True), ('Small Fish Pouch', 3, 'bag', True), ('Hermit Can', 1500, 'fish', False)], 2),
	'Gilded Net': ('tool', True, [('Golden Dubloon', 5, 'material', False), ('Butterfly', 2500, 'bug', False), ('Reinforced Net', 3, 'tool', True)], 2),
	'Average Bug Pouch': ('bag', True, [('Cramped Bug Pouch', 5, 'bag', True), ('Small Bug Pouch', 3, 'bag', True), ('Butterfly', 1600, 'bug', False)], 2),
	'Defenders Dignity': ('armor', True, [('Goldfish', 10000, 'fish', False), ('Golden Plop', 4, 'material', False), ('Distilled Water', 15, 'material', False)], 2),
	'Strung Bludgeon': ('armor', True, [('Bullfrog Horn', 9000, 'material', False), ('Glass Shard', 10, 'material', False), ('Distilled Water', 20, 'material', False)], 2),
	'Average Food Pouch': ('bag', True, [('Cramped Food Pouch', 7, 'bag', True), ('Meat Pie', 250, 'food', False), ('Icing Ironbite', 600, 'food', True), ('Saucy Logfries', 600, 'food', True)], 2),
	'Average Material Pouch': ('bag', True, [('Cramped Material Pouch', 7, 'bag', True), ('Glass Shard', 1, 'material', False), ('Chain Link', 1250, 'material', False)], 2),
	'Platinum Helmet': ('armor', True, [('Jellyfish', 2250, 'fish', False), ('Iron Helmet', 4, 'armor', True), ('Platinum Bar', 750, 'mining', False)], 2),
	'Platinum Platbody': ('armor', True, [('Potato Remains', 5000, 'material', False), ('Iron Platebody', 5, 'armor', True), ('Platinum Bar', 1000, 'mining', False)], 2),
	'Platinum Shins': ('armor', True, [('Sentient Cereal', 5000, 'bug', False), ('Iron Platelegs', 6, 'armor', True), ('Platinum Bar', 1250, 'mining', False)], 2),
	'Platinum Boots': ('armor', True, [('Tropilogs', 7000, 'choppin', False), ('Jellyfish', 3000, 'fish', False), ('Gold Boots', 3, 'armor', True)], 2),
	'Bullet': ('food', True, [('Forest Fibres', 10, 'choppin', False), ('Fly', 10, 'bug', False)], 2),
	'Enforced Slasher': ('weapon', True, [('Nuget Cake', 3, 'material', False), ('Leather Hide', 2500, 'material', False), ('Royal Bayonet', 2, 'weapon', True)], 2),
	'Pharoah Bow': ('weapon', True, [('Woodular Circle', 3, 'material', False), ('Bloach', 1400, 'fish', False), ('Spiked Menace', 2, 'weapon', True)], 2),
	'Crows Nest': ('weapon', True, [('Golden Plop', 3, 'material', False), ('Fruitfly', 4000, 'bug', False), ('Starlight', 2, 'weapon', True)], 2),
	'Platinum Pickaxe': ('tool', True, [('Platinum Bar', 800, 'mining', False), ('Pincer Arm', 10500, 'material', False), ('Gold Pickaxe', 2, 'tool', True)], 2),
	'Sizable Mining Pouch': ('bag', True, [('Platinum Ore', 6750, 'mining', False), ('Average Mining Pouch', 3, 'bag', True)], 2),
	'Plat Hatchet': ('tool', True, [('Tropilogs', 6500, 'choppin', False), ('Chain Link', 5000, 'material', False), ('Golden Axe', 2, 'tool', True)], 2),
	'Sizable Choppin Pouch': ('bag', True, [('Tropilogs', 6750, 'choppin', False), ('Average Choppin Pouch', 3, 'bag', True)], 2),
	'Plat Fishing Rod': ('tool', True, [('Bloach', 2000, 'fish', False), ('Platinum Bar', 800, 'mining', False), ('Gold Fishing Rod', 2, 'tool', True)], 2),
	'Sizable Fish Pouch': ('bag', True, [('Bloach', 2500, 'fish', False), ('Average Fish Pouch', 3, 'bag', True)], 2),
	'Platinet': ('tool', True, [('Fruitfly', 7000, 'bug', False), ('Platinum Ore', 3000, 'mining', False), ('Gilded Net', 2, 'tool', True)], 2),
	'Sizable Bug Pouch': ('bag', True, [('Fruitfly', 6750, 'bug', False), ('Average Bug Pouch', 3, 'bag', True)], 2),
	'Sizable Food Pouch': ('bag', True, [('Golden Meat Pie', 9, 'food', False), ('Nuget Cake', 4, 'material', False), ('Average Food Pouch', 2, 'bag', True)], 2),
	'Sizable Materials Pouch': ('bag', True, [('Golden Plop', 3, 'material', False), ('Woodular Circle', 4, 'material', False), ('Average Material Pouch', 2, 'bag', True)], 2),
	'Anvil Tab 3': ('token', False, [('Platinum Bar', 2000, 'mining', False), ('Bloach', 2000, 'fish', False), ('Fruitfly', 2000, 'bug', False), ('High Steaks', 1500, 'material', False)], 2),
	'Empty Box': ('material', True, [('Hermit Can', 250, 'fish', False), ('Megalodon Tooth', 400, 'material', False), ('Distilled Water', 4, 'material', False)], 2),
	'Googley Eyes': ('material', True, [('Woodular Circle', 2, 'material', False), ('Distilled Water', 5, 'material', False), ('Capitalist Case', 1, 'bag', False)], 2),
	'FMJ Bullet': ('food', True, [('Gold Ore', 15, 'mining', False), ('Bullet', 2, 'food', True)], 2),
	'Viking Cap': ('armor', True, [('Militia Helm', 5, 'armor', True), ('Gold Bar', 400, 'mining', False), ('Glass Shard', 2, 'material', False)], 2),
	'Sleek Coif': ('armor', True, [('Thief Hood', 5, 'armor', True), ('Tropilogs', 2000, 'choppin', False), ('Glass Shard', 2, 'material', False)], 2),
	'Witch Hat': ('armor', True, [('Top Hat', 5, 'armor', True), ('Corn Kernels', 4000, 'material', False), ('Glass Shard', 2, 'material', False)], 2),
	'Studded Hide': ('armor', True, [('Hide Shirt', 4, 'armor', True), ('Megalodon Tooth', 4000, 'material', False), ('Nuget Cake', 1, 'material', False)], 2),
	'Feral Leathering': ('armor', True, [('Fur Shirt', 4, 'armor', True), ('Stick', 3000, 'material', False), ('Nuget Cake', 1, 'material', False)], 2),
	'Furled Robes': ('armor', True, [('Tattered Cloth', 4, 'armor', False), ('Leather Hide', 1500, 'material', False), ('Nuget Cake', 1, 'material', False)], 2),
	'Cavern Trekkers': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Copper Ore', 1500, 'mining', False), ('Iron Ore', 1200, 'mining', False)], 2),
	'Angler Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Goldfish', 1250, 'fish', False), ('Hermit Can', 1000, 'fish', False)], 2),
	'Logger Heels': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Jungle Logs', 1600, 'choppin', False), ('Forest Fibres', 1000, 'choppin', False)], 2),
	'Bandito Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Fly', 2000, 'bug', False), ('Butterfly', 1250, 'bug', False)], 2),
	'Slurpin Herm': ('food', True, [('Hermit Can', 5, 'fish', False), ('Average Strength Potion', 2, 'food', False)], 2),
	'Buttered Toasted Butter': ('food', True, [('Butterfly', 5, 'bug', False), ('Kebab Sticks', 1, 'food', False)], 2),
	'Dootjat Eye': ('material', True, [('Silver Antique', 1, 'material', False), ('Gold Bar', 80, 'mining', False), ('Ghost', 1, 'material', False)], 2),
	'Sandy Satchel': ('bag', True, [('Golden Plop', 1, 'material', False), ('Snakeskinventory Bag', 1, 'bag', False), ('Pocket Sand', 777, 'material', False)], 2),
	'Efaunt Helmet': ('armor', True, [('Ripped Tunic', 20, 'material', False), ('Trimmed Rune Platelegs', 1, 'armor', False), ('Armor Upgrade Stone C', 2, 'material', False), ('Dootjat Eye', 3, 'material', True)], 2),
	'Efaunt Ribcage': ('armor', True, [('Ripped Tunic', 10, 'material', False), ('Midnight Cookie', 10, 'food', False), ('Distilled Water', 25, 'material', False)], 2),
	'Efaunt Hipilium': ('armor', True, [('Ripped Tunic', 7, 'material', False), ('Minuteglass', 3, 'material', False), ('Distilled Water', 25, 'material', False)], 2),
	'Efaunts Broken Ankles': ('armor', True, [('Ripped Tunic', 5, 'material', False), ('Nuget Cake', 3, 'material', False), ('Platinum Boots', 1, 'armor', True)], 2),
	'Efaunt Trunculus': ('armor', True, [('Ribbed Tunic', 4, 'material', False), ('Ripped Tunic', 15, 'material', False), ('Bandage Wraps', 1, 'weapon', True), ('Pharoah Bow', 1, 'weapon', True)], 2),
	'Wooden Traps': ('tool', True, [('Mutant Crabbo', 2, 'critter', False), ('Redox Salts', 20, 'material', False)], 2),
	'Sizable Critter Pouch': ('bag', True, [('Crabbo', 1000, 'critter', False), ('Redox Salts', 15, 'material', False)], 2),
	'Horned Skull': ('tool', True, [('Dune Soul', 1200, 'soul', False), ('Redox Salts', 25, 'material', False)], 2),
	'Sizable Soul Pouch': ('bag', True, [('Dune Soul', 1500, 'soul', False), ('Redox Salts', 20, 'material', False)], 2),
	'Yumyum Desert NPC Completion Token': ('token', True, [('Easy Yumyum Dez NPC Token', 1, 'token', True), ('Med Yumyum Dez NPC Token', 1, 'token', True), ('Hard Yumyum Dez NPC Token', 1, 'token', True)], 2),
	'Yumyum Skills Completion Token': ('token', True, [('Bloach', 4000, 'fish', False), ('Fruitfly', 8000, 'bug', False), ('Dense Water', 50, 'material', False)], 2),
	'Yumyum Misc Completion Token': ('token', True, [('Minuteglass', 13, 'material', False), ('Ghost', 25, 'material', False), ('Efaunt Helmet', 1, 'armor', True), ('Fuscismatia', 2, 'armor', False)], 2),
	'Star Talent Reset Potion': ('material', True, [('Talent Point Reset Fragment', 25, 'material', False), ('Distilled Water', 5, 'material', False)], 2),
	'Easy Yumyum Dez NPC Token': ('token', True, [('Bandit Bob Token', 1, 'token', False), ('Snake Jar Token', 1, 'token', False), ('Whattso Token', 1, 'token', False), ('Cowbo Jones Token', 1, 'token', False)], 2),
	'Med Yumyum Dez NPC Token': ('token', True, [('Carpetiem Token', 1, 'token', False), ('Goldric Token', 1, 'token', False), ('Fishpaste Token', 1, 'token', False), ('Cattleprod Token', 1, 'token', False)], 2),
	'Hard Yumyum Dez NPC Token': ('token', True, [('Loominadi Token', 1, 'token', False), ('Djonnut Token', 1, 'token', False), ('Scubidew Token', 1, 'token', False), ('Wellington Token', 1, 'token', False)], 2),
	'Dementia Helmet': ('armor', True, [('Froge', 5000, 'critter', False), ('Platinum Helmet', 2, 'armor', True), ('Dementia Bar', 300, 'mining', False)], 3),
	'Dementia Body': ('armor', True, [('Forest Soul', 1000, 'soul', False), ('Platinum Platbody', 2, 'armor', True), ('Dementia Bar', 350, 'mining', False)], 3),
	'Dementia Shins': ('armor', True, [('Floof Ploof', 8000, 'material', False), ('Platinum Shins', 2, 'armor', True), ('Dementia Bar', 400, 'mining', False)], 3),
	'Dementia Boots': ('armor', True, [('Poison Froge', 3, 'critter', False), ('Platinum Boots', 1, 'armor', True), ('Dementia Bar', 500, 'mining', False)], 3),
	'Uninflated Glove': ('weapon', True, [('Melty Cube', 70000, 'material', False), ('Bandage Wraps', 3, 'weapon', True)], 3),
	'The Ice Breaker': ('weapon', True, [('Melty Cube', 25000, 'material', False), ('Enforced Slasher', 2, 'weapon', True), ('Redox Salts', 150, 'material', False)], 3),
	'Blizzard Bow': ('weapon', True, [('Forest Soul', 7000, 'soul', False), ('Pharoah Bow', 2, 'weapon', True), ('Redox Salts', 150, 'material', False)], 3),
	'Spriggly Storm': ('weapon', True, [('Tundra Logs', 10000, 'choppin', False), ('Crows Nest', 2, 'weapon', True), ('Redox Salts', 150, 'material', False)], 3),
	'Dementia Pickaxe': ('tool', True, [('Dementia Bar', 275, 'mining', False), ('Moustache Comb', 15000, 'tool', False), ('Platinum Pickaxe', 2, 'tool', True)], 3),
	'Big Mining Pouch': ('bag', True, [('Dementia Ore', 17500, 'mining', False), ('Sizable Mining Pouch', 2, 'bag', True)], 3),
	'Dementia Dicer': ('tool', True, [('Tundra Logs', 15000, 'choppin', False), ('Redox Salts', 50, 'material', False), ('Plat Hatchet', 2, 'tool', True)], 3),
	'Big Choppin Pouch': ('bag', True, [('Tundra Logs', 20000, 'choppin', False), ('Sizable Choppin Pouch', 2, 'bag', True)], 3),
	'Dementia Rod for Fishing': ('tool', True, [('Dementia Bar', 300, 'mining', False), ('Redox Salts', 50, 'material', False), ('Plat Fishing Rod', 2, 'tool', True)], 3),
	'Big Fish Pouch': ('bag', True, [('Crescent Scropie', 4, 'critter', False), ('Redox Salts', 50, 'material', False), ('Sizable Fish Pouch', 2, 'bag', True)], 3),
	'Dementia Net': ('tool', True, [('Mosquisnow', 15000, 'bug', False), ('Redox Salts', 50, 'material', False), ('Platinet', 2, 'tool', True)], 3),
	'Big Bug Pouch': ('bag', True, [('Mosquisnow', 10000, 'bug', False), ('Sizable Bug Pouch', 2, 'bag', True)], 3),
	'Natural Traps': ('tool', True, [('Nakeo Moleo', 5, 'critter', False), ('Redox Salts', 50, 'material', False), ('Wooden Traps', 2, 'tool', True)], 3),
	'Big Critter Pouch': ('bag', True, [('Mousey', 10000, 'critter', False), ('Sizable Critter Pouch', 2, 'bag', True)], 3),
	'Prickle Skull': ('tool', True, [('Rooted Soul', 7000, 'soul', False), ('Redox Salts', 50, 'material', False), ('Horned Skull', 2, 'tool', True)], 3),
	'Big Soul Pouch': ('bag', True, [('Rooted Soul', 8000, 'soul', False), ('Sizable Soul Pouch', 2, 'bag', True)], 3),
	'Big Food Pouch': ('bag', True, [('Slurpin Herm', 1500, 'food', True), ('Buttered Toasted Butter', 1500, 'food', True), ('Yeti Ham', 10000, 'material', False), ('Sizable Food Pouch', 2, 'bag', True)], 3),
	'Big Materials Pouch': ('bag', True, [('Sticky Stick', 15000, 'material', False), ('Ice Age 3', 3, 'material', False), ('Sizable Materials Pouch', 2, 'bag', True)], 3),
	'Void Imperium Helmet': ('armor', True, [('Spontaneity Salts', 500, 'material', False), ('Dementia Helmet', 2, 'armor', True), ('Void Bar', 1000, 'mining', False), ('Dense Water', 5, 'material', False)], 3),
	'Void Imperium Platebody': ('armor', True, [('Audio Cord', 75000, 'material', False), ('Dementia Body', 2, 'armor', True), ('Void Bar', 500, 'mining', False), ('Dense Water', 4, 'material', False)], 3),
	'Void Imperium Shardshins': ('armor', True, [('Wispy Lumber', 75000, 'choppin', False), ('Dementia Shins', 2, 'armor', True), ('Void Bar', 650, 'mining', False), ('Dense Water', 4, 'material', False)], 3),
	'Void Imperium Kicks': ('armor', True, [('Flycicle', 60000, 'bug', False), ('Dementia Boots', 2, 'armor', True), ('Void Bar', 725, 'mining', False), ('Dense Water', 4, 'material', False)], 3),
	'Eclectic Ordeal': ('weapon', True, [('Yellow Snowflake', 100, 'material', False), ('Minervowl', 50, 'critter', False), ('Dootjat Eye', 10, 'material', True), ('Dense Water', 15, 'material', False)], 3),
	'Deuscythe': ('weapon', True, [('Black Lense', 10, 'material', False), ('Eternal Lord of The Undying Ember', 15, 'critter', False), ('The Ice Breaker', 3, 'weapon', True), ('Dense Water', 7, 'material', False)], 3),
	'Blackhole Bow': ('weapon', True, [('Black Lense', 4, 'material', False), ('Spontaneity Salts', 350, 'material', False), ('Blizzard Bow', 3, 'weapon', True), ('Dense Water', 7, 'material', False)], 3),
	'Grey Gatsby': ('weapon', True, [('Black Lense', 4, 'material', False), ('Frigid Soul', 8000, 'soul', False), ('Spriggly Storm', 3, 'weapon', True), ('Dense Water', 7, 'material', False)], 3),
	'Void Imperium Pik': ('tool', True, [('Void Bar', 400, 'mining', False), ('Dementia Pickaxe', 2, 'tool', True), ('Dense Water', 5, 'material', False)], 3),
	'Large Mining Pouch': ('bag', True, [('Void Ore', 25000, 'mining', False), ('Big Mining Pouch', 2, 'bag', True)], 3),
	'Void Imperium Axe': ('tool', True, [('Wispy Lumber', 50000, 'choppin', False), ('Dementia Dicer', 2, 'tool', True), ('Dense Water', 5, 'material', False)], 3),
	'Large Choppin Pouch': ('bag', True, [('Wispy Lumber', 30000, 'choppin', False), ('Big Choppin Pouch', 2, 'bag', True)], 3),
	'Void Imperium Rod': ('tool', True, [('Spontaneity Salts', 200, 'material', False), ('Minervowl', 3, 'critter', False), ('Dementia Rod for Fishing', 2, 'tool', True), ('Dense Water', 5, 'material', False)], 3),
	'Large Fish Pouch': ('bag', True, [('Bloach', 50000, 'fish', False), ('Big Fish Pouch', 2, 'bag', True)], 3),
	'Void Imperium Net': ('tool', True, [('Flycicle', 50000, 'bug', False), ('Dementia Net', 2, 'tool', True), ('Dense Water', 5, 'material', False)], 3),
	'Large Bug Pouch': ('bag', True, [('Flycicle', 35000, 'bug', False), ('Big Bug Pouch', 2, 'bag', True)], 3),
	'Steel Traps': ('tool', True, [('Eternal Lord of The Undying Ember', 6, 'critter', False), ('Natural Traps', 1, 'tool', True), ('Dense Water', 5, 'material', False)], 3),
	'Large Critter Pouch': ('bag', True, [('Pingy', 30000, 'critter', False), ('Big Critter Pouch', 2, 'bag', True)], 3),
	'Manifested Skull': ('tool', True, [('Frigid Soul', 12000, 'soul', False), ('Prickle Skull', 2, 'tool', True), ('Dense Water', 5, 'material', False)], 3),
	'Large Soul Pouch': ('bag', True, [('Rooted Soul', 30000, 'soul', False), ('Big Soul Pouch', 2, 'bag', True)], 3),
	'Large Food Pouch': ('bag', True, [('Golden Ham', 10, 'food', False), ('Critter Numnums', 30, 'food', True), ('Soulble Gum', 30, 'food', True), ('Big Food Pouch', 1, 'bag', True)], 3),
	'Large Materials Pouch': ('bag', True, [('Audio Cord', 70000, 'material', False), ('Black Lense', 3, 'material', False), ('Big Materials Pouch', 2, 'bag', True)], 3),
	'Anvil Tab 4': ('token', False, [('Not Yet', 6, 'filler', False), ('Frigid Soul', 22, 'soul', False), ('Eternal Lord of The Undying Ember', 1, 'critter', False), ('Spontaneity Salts', 1, 'material', False)], 3),
	'Mark of Member': ('armor', True, [('Grandma Disguise', 1, 'armor', False), ('Void Imperium Helmet', 1, 'armor', True), ('Dioxide Synthesis', 500, 'material', False)], 3),
	'Murmillo Helm': ('armor', True, [('Dioxide Synthesis', 500, 'material', False), ('Void Imperium Helmet', 1, 'armor', True)], 3),
	'Conquistador Plume': ('armor', True, [('Dioxide Synthesis', 500, 'material', False), ('Void Imperium Helmet', 1, 'armor', True)], 3),
	'Adornment of the High Priest': ('armor', True, [('Dioxide Synthesis', 500, 'material', False), ('Void Imperium Helmet', 1, 'armor', True)], 3),
	'Member Hoodie': ('armor', True, [('Dioxide Synthesis', 500, 'material', False), ('Uninflated Glove', 2, 'weapon', True), ('Void Imperium Platebody', 1, 'armor', True)], 3),
	'Damascus Plates': ('armor', True, [('Dioxide Synthesis', 500, 'material', False), ('Void Imperium Platebody', 1, 'armor', True)], 3),
	'Evergreen Wraps': ('armor', True, [('Dioxide Synthesis', 500, 'material', False), ('Void Imperium Platebody', 1, 'armor', True)], 3),
	'Elegantine Robes': ('armor', True, [('Dioxide Synthesis', 500, 'material', False), ('Void Imperium Platebody', 1, 'armor', True)], 3),
	'Critter Numnums': ('food', True, [('Crabbo', 100, 'critter', False), ('Distilled Water', 1, 'material', False)], 3),
	'Soulble Gum': ('food', True, [('Dune Soul', 70, 'soul', False), ('Distilled Water', 1, 'material', False)], 3),
	'Shivering Sack': ('bag', True, [('Mamooth Hide Bag', 1, 'bag', False), ('Melty Cube', 2000, 'material', False), ('Yellow Snowflake', 3, 'material', False)], 3),
}


MATERIALS = {
    'World 1': {
        'Anvil': ['Thread', 'Trusty Nails', 'Boring Brick', 'Chain Link', 'Leather Hide'],
        'Boss': ['Amarok Slab', 'Chaotic Amarok Slab'],
        'Chopping': ['Oak Logs', 'Grass Leaf', 'Bleach Logs', 'Jungle Logs', 'Forest Fibres', 'Potty Rolls'],
		'Critter': ['Froge', 'Poison Froge', 'Minervowl', 'Mousey', 'Nakeo Moleo'],
        'Foods': ['Nomwich', 'Hot Dog', 'Golden Meat Pie'],
        'Mining': ['Crude Oil', 'Copper Ore', 'Copper Bar', 'Iron Ore', 'Iron Bar', 'Gold Ore', 'Gold Bar', 'Platinum Ore', 'Platinum Bar', 'Dementia Ore', 'Dementia Bar', 'Void Ore', 'Void Bar'],
        'Monster Drops': ['Spore Cap', 'Frog Leg', 'Bean Slices', 'Slime Sludge', 'Carrot Cube', 'Red Spore Cap', 'Goblin Ear', 'Plank', 'Bullfrog Horn', 'Stick', 'Corn Kernels'],
        'Other': ['Crimson String', 'Cue Tape', 'Tattered Cloth', 'Silver Antique'],
        'Potions': ['Small Life Potion', 'Small Mana Potion', 'Average Strength Potion'],
        "Tokens": ['Glumlee Token', 'Picnic Token', 'Woodsman Token', 'Stiltzcho Token', 'Krunk Token',  'TP Pete Token',  'Funguy Token', 'Dazey Token', 'Tiki Chief Token', 'Sproutinald Token', 'Dog Bone Token', 'Papua Piggea Token',],
        'Unique Drops': ['Spore Tee', 'Dank Paypay Chest', 'Snakeskinventory Bag', 'Carrot Launcher', 'Woodular Circle', 'Grandma Disguise', 'Golden Plop'],
		'Worship': ['Forest Soul', 'Rooted Soul']
    },
    'World 2': {
		'Boss': ['Ripped Tunic', 'Ribbed Tunic'],
        'Catching': ['Fly', 'Butterfly', 'Sentient Cereal', 'Fruitfly'],
        'Chopping': ['Tropilogs'],
		'Critter': ['Crabbo', 'Mutant Crabbo', 'Crescent Scropie'],
        'Fishing': ['Goldfish', 'Hermit Can', 'Jellyfish', 'Bloach'],
        'Foods': ['Kebab Sticks', 'Meat Pie'],
        'Monster Drops': ['Pocket Sand', 'Megalodon Tooth', 'Crabby Cakey', 'Pincer Arm', 'Potato Remains', 'High Steaks',],
        'Other': ['Golden Dubloon', 'Distilled Water'],
        'Unique Drops': ['Glass Shard', 'Nuget Cake', 'Ghost'],
		'Worship': ['Dune Soul']
    },
	'World 3': {
		'Catching': ['Mosquisnow', 'Flycicle'],
		'Chopping': ['Tundra Logs' 'Wispy Lumber'],
		'Critter': ['Pingy', 'Eternal Lord of The Undying Ember'],
		'Foods': ['Golden Ham'],
		'Monster Drops': ['Floof Ploof', 'Melty Cube', 'Moustache Comb', 'Sticky Stick', 'Audio Cord', 'Yeti Ham', 'Black Lense'],
		'Refinery': ['Redox Salts', 'Spontaneity Salts', 'Dioxide Synthesis'],
		'Unique Drops': ['Ice Age 3', 'Mamooth Hide Bag'],
		'Worship': ['Frigid Soul']
	}
}

MATERIAL_WEIGHTS = [
	('Copper Ore', 'Oak Logs', 'Small Life Potion', 'Small Mana Potion', 'Average Strength Potion', 'Spore Cap', 'Frog Leg', 'Crude Oil', 'Cue Tape', 'Crimson String', 'Nomwich', 'Hot Dog', 'Meat Pie', 'Thread', 'Froge', 'Grass Leaf', 'Dank Paypay Chest'),
	('Copper Bar', 'Iron Ore', 'Bleach Logs', 'Bean Slices', 'Slime Sludge', 'Forest Soul', 'Trusty Nails', 'Poison Froge', 'Crabbo', 'Redox Salts', 'Silver Antique', 'Kebab Sticks', 'Capitalist Case'),
	('Iron Bar', 'Jungle Logs', 'Carrot Cube', 'Goblin Ear', 'Dune Soul', 'Boring Brick', 'Fly', 'Goldfish', 'Mutant Crabbo', 'Spore Tee', 'Forest Fibres', 'Tattered Cloth', 'Distilled Water', 'Red Spore Cap', 'Snakeskinventory Bag', 'Golden Dubloon', 'Bolt Cutters'),
	('Gold Ore', 'Tropilogs', 'Plank', 'Stick', 'Bullfrog Horn', 'Chain Link', 'Butterfly', 'Hermit Can', 'Corn Kernels', 'Glass Shard', 'Woodular Circle', 'Nuget Cake'),
	('Gold Bar', 'Veiny Logs', 'Amarok Slab', 'Pocket Sand', 'Megalodon Tooth', 'Rooted Soul', 'Leather Hide', 'Sentient Cereal', 'Jellyfish', 'Crescent Scropie', 'Mousey', 'Potty Rolls', 'Carrot Launcher', 'Ghost', 'Midnight Cookie', 'Dense Water', 'Talent Point Reset Fragment'),
	('Platinum Ore', 'Crabby Cakey', 'Fruitfly', 'Bloach', 'Nakeo Moleo', 'Minuteglass', 'Golden Meat Pie', 'Golden Plop'),
	('Platinum Bar', 'Pincer Arm', 'Potato Remains', 'Frigid Soul', 'Minervowl', 'Pingy', 'Grandma Disguise', 'Armor Upgrade Stone C'),
	('High Steaks', 'Mosquisnow', 'Eternal Lord of The Undying Ember', 'Ripped Tunic', 'Ribbed Tunic'),
	('Dementia Ore', 'Spontaneity Salts', 'Melty Cube', 'Fuscismatia'),
	('Dementia Bar', 'Flycicle', 'Sticky Stick'),
	('Tundra Logs', 'Dioxide Synthesis', 'Floof Ploof'),
	('Void Ore', 'Yellow Snowflake', 'Moustache Comb', 'Golden Ham'),
	('Void Bar', 'Ice Age 3'),
	('Wispy Lumber', 'Yeti Ham'),
	('Trimmed Rune Platelegs'),
	('Black Lense', 'Audio Cord', 'Mamooth Hide Bag'),
	('Chaotic Amarok Slab'),
	(),
	(),
	('Not Yet')
]