"""
Formatting

recipe Name: (item type, is craftable, resources)

resources -> [(resource name, quantity needed, resource type, has recipe), ...]
"""

RECIPES = {
    'Boxing Gloves': ('weapon', True, [('Crimson String', 1, 'material', False), ('Cue Tape', 5, 'material', False)]),
    'Wooden Spear': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Copper Bar', 10, 'mining', False)]),
    'Wooden Bow': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Thread', 30, 'material', False)]), 
    'Gnarled Wand': ('weapon', True, [('Spore Cap', 25, 'material', False), ('Oak Logs', 30, 'choppin', False)]), 
    'Farmer Brim': ('armor', True, [('Spore Cap', 15, 'material', False), ('Copper Ore', 20, 'mining', False)]), 
    'Orange Tee': ('armor', True, [('Spore Cap', 30, 'material', False), ('Oak Logs', 25, 'choppin', False)]), 
    'Torn Jeans': ('armor', True, [('Frog Leg', 30, 'material', False), ('Copper Bar', 10, 'mining', False), ('Thread', 20, 'material', False)]),
    'Flip Flops': ('armor', True, [('Bean Slices', 50, 'material', False), ('Copper Bar', 40, 'mining', False), ('Grass Leaf', 50, 'choppin', False)]),
    'Copper Pickaxe': ('tool', True, [('Copper Bar', 20, 'mining', False), ('Frog Leg', 50, 'material', False)]), 
    'Cramped Mining Pouch': ('bag', True, [('Copper Ore', 150, 'mining', False)]), 
    'Copper Chopper': ('tool', True, [('Copper Bar', 20, 'mining', False), ('Oak Logs', 30, 'choppin', False), ('Thread', 30, 'material', False)]), 
    'Cramped Choppin Pouch': ('bag', True, [('Oak Logs', 200, 'choppin', False), ('Trusty Nails', 40, 'material', False)]), 
    'Leather Cap': ('armor', True, [('Frog Leg', 25, 'material', False), ('Oak Logs', 75, 'choppin', False), ('Thread', 25, 'material', False)]),
    'The Stingers': ('weapon', True, [('Copper Bar', 30, 'mining', False), ('Oak Logs', 100, 'choppin', False), ('Trusty Nails', 50, 'material', False)]),
    'Cramped Food Pouch': ('bag', True, [('Nomwich', 75, 'food', False), ('Hot Dog', 25, 'food', False), ('Oak Logs', 75, 'choppin', False), ('Copper Bar', 20, 'mining', False)]),
    'Cramped Material Pouch': ('bag', True, [('Trusty Nails', 125, 'material', False), ('Frog Leg', 50, 'material', False), ('Bean Slices', 50, 'material', False)]),
    'Copper Helmet': ('armor', True, [('Copper Bar', 75, 'mining', False), ('Bean Slices', 75, 'material', False)]),
    'Copper Platebody': ('armor', True, [('Copper Bar', 90, 'mining', False), ('Trusty Nails', 150, 'material', False)]),
    'Copper Platelegs': ('armor', True, [('Copper Bar', 110, 'mining', False), ('Bleach Logs', 200, 'choppin', False)]),
    'Copper Boots': ('armor', True, [('Copper Bar', 200, 'mining', False)]),
    'Militia Helm': ('armor', True, [('Iron Bar', 35, 'mining', False), ('Copper Ore', 300, 'mining', False), ('Copper Helmet', 2, 'armor', True)]),
    'Thief Hood': ('armor', True, [('Iron Bar', 35, 'mining', False), ('Thread', 300, 'material', False), ('Copper Helmet', 2, 'armor', True)]),
    'Top Hat': ('armor', True, [('Iron Bar', 35, 'mining', False), ('Oak Logs', 550, 'choppin', False), ('Copper Helmet', 2, 'armor', True)]),
    'Party Hat': ('armor', False, [('Iron Bar', 200, 'mining', False), ('Copper Helmet', 4, 'armor', True)]),
    'Steel Axe': ('weapon', True, [('Slime Sludge', 300, 'material', False), ('Boring Brick', 200, 'material', False)]),
    'Birch Longbow': ('weapon', True, [('Slime Sludge', 300, 'material', False), ('Bleach Logs', 400, 'choppin', False)]),
    'Quarterstaff': ('weapon', True, [('Slime Sludge', 300, 'material', False), ('Copper Bar', 175, 'mining', False)]),
    'Copper Band': ('armor', True, [('Copper Bar', 1000, 'mining', False)]),
    'Iron Pickaxe': ('tool', True, [('Iron Bar', 175, 'mining', False), ('Carrot Cube', 300, 'material', False)]),
    'Small Mining Pouch': ('bag', True, [('Iron Ore', 850, 'mining', False)]),
    'Iron Hatchet': ('tool', True, [('Jungle Logs', 450, 'choppin', False), ('Boring Brick', 250, 'material', False)]),
    'Small Choppin Pouch': ('bag', True, [('Bleach Logs', 850, 'choppin', False)]),
    'Iron Helmet': ('armor', True, [('Iron Bar', 225, 'mining', False), ('Goblin Ear', 400, 'material', False)]),
    'Iron Platebody': ('armor', True, [('Iron Bar', 275, 'mining', False), ('Jungle Logs', 800, 'choppin', False)]),
    'Iron Platelegs': ('armor', True, [('Iron Bar', 300, 'mining', False), ('Boring Brick', 300, 'material', False)]),
    'Anvil Tab 2': ('misc', False, [('Iron Bar', 500, 'mining', False), ('Chain Link', 200, 'material', False), ('Forest Fibres', 400, 'choppin', False), ('Bullfrog Horn', 250, 'material', False)]),
    'Blue Tee': ('armor', True, [('Spore Cap', 50, 'material', False), ('Oak Logs', 50, 'choppin', False), ('Orange Tee', 3, 'armor', True)]),
    'Sleek Shank': ('armor', True, [('Thread', 300, 'material', False), ('Wooden Spear', 3, 'weapon', True), ('Wooden Bow', 3, 'weapon', True), ('Gnarled Wand', 3, 'weapon', True)]),
    'Iron Boots': ('armor', True, [('Trusty Nails', 500, 'material', False), ('Iron Bar', 125, 'mining', False), ('Copper Boots', 2, 'armor', True)]),
    'Steel Band': ('armor', True, [('Iron Bar', 600, 'mining', False)]),
    'Purple Tupacband': ('armor', True, [('Bleach Logs', 150, 'choppin', False), ('Iron Ore', 75, 'mining', False), ('Crude Oil', 100, 'mining', False)]),
    'Icing Ironbite': ('food', True, [('Iron Ore', 5, 'mining', False), ('Small Mana Potion', 2, 'food', False)]), 
    'Saucy Logfries': ('food', True, [('Jungle Logs', 6, 'choppin', False), ('Small Life Potion', 3, 'food', False)]), 
    'Goo Galoshes': ('armor', True, [('Slime Sludge', 600, 'material', False), ('Jungle Logs', 1000, 'choppin', False), ('Copper Boots', 2, 'armor', True)]),
    'Fur Shirt': ('armor', True, [('Goblin Ear', 500, 'material', False), ('Iron Bar', 500, 'mining', False)]), 
    'Hide Shirt': ('armor', True, [('Bleach Logs', 325, 'choppin', False), ('Copper Platebody', 2, 'armor', True), ('Steel Axe', 1, 'weapon', True)]), 
    'Eco Friendly Oil': ('mining', True, [('Crude Oil', 1, 'mining', False), ('Grass Leaf', 1, 'choppin', False)]), 
    'Dooble Goopi': ('armor', True, [('Slime Sludge', 1000, 'material', False), ('Copper Band', 1, 'armor', True), ('Steel Band', 1, 'armor', True)]), 
    'Bleached Designer Wode Patch Pants': ('armor', True, [('Torn Jeans', 10, 'armor', True), ('Plank', 400, 'material', False), ('Bleach Logs', 900, 'choppin', False)]), 
    'Dirty Coal Miner Baggy Soot Pants': ('armor', True, [('Torn Jeans', 8, 'armor', True), ('Iron Ore', 250, 'mining', False)]), 
    'Peanut': ('food', True, [('Hot Dog', 2, 'food', False), ('Copper Ore', 1, 'mining', False), ('Bleach Logs', 1, 'choppin', False)]), 
    'Golden Peanut': ('food', False, [('Not Yet', 1, '', False), ('Copper Ore', 1, 'mining', False)]), 
    'Blunderbag': ('bag', True, [('Spore Tee', 3, 'armor', False), ('Dank Paypay Chest', 1, 'bag', False), ('Spore Cap', 200, 'material', False)]), 
    'Purple Tee': ('armor', True, [('Red Spore Cap', 40, 'material', False), ('Bleach Logs', 100, 'choppin', False), ('Orange Tee', 3, 'armor', True)]), 
    'Green Tee': ('armor', True, [('Thread', 150, 'material', False), ('Spore Tee', 2, 'armor', False), ('Orange Tee', 3, 'armor', True)]), 
    'Black Tee': ('armor', True, [('Orange Tee', 5, 'armor', True), ('Blue Tee', 3, 'armor', True), ('Purple Tee', 3, 'armor', True), ('Green Tee', 3, 'armor', True)]), 
    'Blunderhills NPC Completion Token': ('misc', False, [('Easy Blunderhills NPC Token', 1, 'misc', False), ('Med Blunderhills NPC Token', 1, 'misc', False), ('Hard Blunderhills NPC Token', 1, 'misc', False)]), 
    'Blunder Skills Completion Token': ('misc', False, [('Not Yet', 1, '', False), ('Not Yet', 2, '', False)]), 
    'Blunderhills Misc Completion Token': ('misc', False, [('Not Yet', 1, '', False), ('Not Yet', 1, '', False)]), 
    'Easy Blunderhills NPC Token': ('misc', False, [('Woodsman Token', 1, 'misc', False), ('Glumlee Token', 1, 'misc', False), ('Stiltzcho Token', 1, 'misc', False), ('Funguy Token', 1, 'misc', False)]), 
    'Med Blunderhills NPC Token': ('misc', False, [('Krunk Token', 1, 'misc', False), ('Tiki Chief Token', 1, 'misc', False), ('Dog Bone Token', 1, 'misc', False), ('Papua Piggea Token', 1, 'misc', False)]), 
    'Hard Blunderhills NPC Token': ('misc', False, [('Picnic Token', 69, 'misc', False), ('TP Pete Token', 1, 'misc', False), ('Sproutinald Token', 1, 'misc', False), ('Dazey Token', 1, 'misc', False)]), 
    'Amarok Helmet': ('armor', True, [('Amarok Slab', 20, 'inf', False), ('Forest Fibres', 3000, 'choppin', False), ('Woodular Circle', 8, 'material', False)]), 
    'Amarok Bodyplate': ('armor', True, [('Amarok Slab', 10, 'inf', False), ('Iron Bar', 500, 'mining', False), ('Corn Kernels', 1200, 'material', False)]), 
    'Amarok Hinds': ('armor', True, [('Amarok Slab', 6, 'inf', False), ('Chain Link', 500, 'material', False), ('Bullfrog Horn', 1000, 'material', False)]), 
    'Amarok Paws': ('armor', True, [('Amarok Slab', 5, 'inf', False), ('Grass Leaf', 250, 'choppin', False), ('Iron Boots', 1, 'armor', True)]), 
    'Chaotic Amarok Pendant': ('armor', True, [('Chaotic Amarok Slab', 4, 'inf', False), ('Amarok Slab', 10, 'inf', False), ('Distilled Water', 25, 'material', False)]), 
    'Copper Fish Rod': ('tool', True, [('Copper Bar', 200, 'mining', False), ('Goldfish', 400, 'fish', False)]), 
    'Cramped Fish Pouch': ('bag', True, [('Goldfish', 180, 'fish', False)]), 
    'Copper Netted Net': ('tool', True, [('Jungle Logs', 500, 'choppin', False), ('Fly', 400, 'bug', False)]), 
    'Cramped Bug Pouch': ('bag', True, [('Fly', 180, 'bug', False)]),
    'Iron Fishing Rod': ('tool', True, [('Iron Bar', 300, 'mining', False), ('Hermit Can', 850, 'fish', False), ('Distilled Water', 3, 'material', False)]), 
    'Small Fish Pouch': ('bag', True, [('Hermit Can', 425, 'fish', False), ('Distilled Water', 2, 'material', False)]), 
    'Reinforced Net': ('tool', True, [('Forest Fibres', 800, 'choppin', False), ('Butterfly', 850, 'bug', False), ('Distilled Water', 3, 'material', False)]), 
    'Small Bug Pouch': ('bag', True, [('Butterfly', 425, 'bug', False), ('Distilled Water', 2, 'material', False)]), 
    'Gold Helmet': ('armor', True, [('Fly', 2000, 'bug', False), ('Copper Helmet', 4, 'armor', True), ('Gold Bar', 400, 'mining', False)]), 
    'Gold Platebody': ('armor', True, [('Pocket Sand', 1500, 'material', False), ('Copper Platebody', 5, 'armor', True), ('Gold Bar', 475, 'mining', False)]), 
    'Gold Platelegs': ('armor', True, [('Goldfish', 500, 'fish', False), ('Copper Platelegs', 6, 'armor', True), ('Gold Bar', 550, 'mining', False)]), 
    'Gold Boots': ('armor', True, [('Gold Bar', 400, 'mining', False), ('Iron Boots', 2, 'armor', True), ('Distilled Water', 8, 'material', False)]), 
    'Bandage Wraps': ('weapon', True, [('Cue Tape', 5000, 'material', False), ('The Stingers', 10, 'weapon', True), ('Potty Rolls', 2000, 'choppin', False)]), 
    'Royal Bayonet': ('weapon', True, [('Forest Fibres', 1250, 'choppin', False), ('Steel Axe', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)]), 
    'Spiked Menace': ('weapon', True, [('Gold Bar', 250, 'mining', False), ('Birch Longbow', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)]),
    'Starlight': ('weapon', True, [('Chain Link', 1000, 'material', False), ('Quarterstaff', 3, 'weapon', True), ('Distilled Water', 8, 'material', False)]), 
    'Gold Pickaxe': ('tool', True, [('Golden Dubloon', 5, 'inf', False), ('Megalodon Tooth', 2500, 'material', False), ('Gold Bar', 1000, 'mining', False), ('Iron Pickaxe', 5, 'tool', True)]), 
    'Average Mining Pouch': ('bag', True, [('Cramped Mining Pouch', 10, 'bag', True), ('Small Mining Pouch', 4, 'bag', True), ('Gold Bar', 1000, 'mining', False)]), 
    'Golden Axe': ('tool', True, [('Golden Dubloon', 5, 'inf', False), ('Crabby Cakey', 2000, 'material', False), ('Iron Hatchet', 5, 'tool', True)]), 
    'Average Choppin Pouch': ('bag', True, [('Cramped Choppin Pouch', 10, 'bag', True), ('Small Choppin Pouch', 5, 'bag', True), ('Forest Fibres', 1800, 'choppin', False)]), 
    'Gold Fishing Rod': ('tool', True, [('Hermit Can', 2500, 'fish', False), ('Leather Hide', 1000, 'material', False), ('Iron Fishing Rod', 5, 'tool', True)]), 
    'Average Fish Pouch': ('bag', True, [('Cramped Fish Pouch', 10, 'bag', True), ('Small Fish Pouch', 5, 'bag', True), ('Hermit Can', 1500, 'fish', False)]), 
    'Gilded Net': ('tool', True, [('Butterfly', 2500, 'bug', False), ('Gold Bar', 1250, 'mining', False), ('Reinforced Net', 5, 'tool', True)]), 
    'Average Bug Pouch': ('bag', True, [('Cramped Bug Pouch', 10, 'bag', True), ('Small Bug Pouch', 5, 'bag', True), ('Butterfly', 1600, 'bug', False)]), 
    'Defenders Dignity': ('armor', True, [('Goldfish', 16000, 'fish', False), ('Golden Plop', 17, 'material', False), ('Distilled Water', 15, 'material', False)]), 
    'Strung Bludgeon': ('armor', True, [('Bullfrog Horn', 9000, 'material', False), ('Glass Shard', 10, 'material', False), ('Distilled Water', 20, 'material', False)]), 
    'Average Food Pouch': ('bag', True, [('Cramped Food Pouch', 10, 'bag', True), ('Meat Pie', 250, 'food', False), ('Icing Ironbite', 600, 'food', True), ('Saucy Logfries', 600, 'food', True)]), 
    'Average Material Pouch': ('bag', True, [('Cramped Material Pouch', 10, 'bag', True), ('Glass Shard', 1, 'material', False), ('Chain Link', 1250, 'material', False)]), 
    'Platinum Helmet': ('armor', True, [('Jellyfish', 4000, 'fish', False), ('Iron Helmet', 4, 'armor', True), ('Platinum Bar', 750, 'mining', False)]), 
    'Platinum Platbody': ('armor', True, [('Potato Remains', 5000, 'material', False), ('Iron Platebody', 5, 'armor', True), ('Platinum Bar', 1000, 'mining', False)]), 
    'Platinum Shins': ('armor', True, [('Sentient Cereal', 500, 'bug', False), ('Iron Platelegs', 6, 'armor', True), ('Platinum Bar', 1250, 'mining', False)]), 
    'Platinum Boots': ('armor', True, [('Tropilogs', 7500, 'choppin', False), ('Jellyfish', 10000, 'fish', False)]),
    'Bullet': ('food', True, [('Forest Fibres', 10, 'choppin', False), ('Fly', 10, 'bug', False)]),
    'Enforced Slasher': ('weapon', True, [('Nuget Cake', 10, 'material', False), ('Leather Hide', 12000, 'material', False), ('Royal Bayonet', 3, 'weapon', True)]),
    'Pharoah Bow': ('weapon', True, [('Woodular Circle', 10, 'material', False), ('Bloach', 10000, 'fish', False), ('Spiked Menace', 3, 'weapon', True)]),
    'Crows Nest': ('weapon', True, [('Golden Plop', 10, 'material', False), ('Fruitfly', 10000, 'bug', False), ('Starlight', 3, 'weapon', True)]),
    'Platinum Pickaxe': ('tool', True, [('Platinum Bar', 3500, 'mining', False), ('Pincer Arm', 10500, 'material', False), ('Gold Pickaxe', 3, 'tool', True)]),
    'Sizable Mining Pouch': ('bag', True, [('Platinum Ore', 6750, 'mining', False), ('Average Mining Pouch', 5, 'bag', True)]),
    'Plat Hatchet': ('tool', True, [('Tropilogs', 8000, 'choppin', False), ('Chain Link', 6000, 'material', False), ('Golden Axe', 3, 'tool', True)]),
    'Sizable Choppin Pouch': ('bag', True, [('Tropilogs', 6750, 'choppin', False), ('Average Choppin Pouch', 5, 'bag', True)]),
    'Plat Fishing Rod': ('tool', True, [('Bloach', 12000, 'fish', False), ('Platinum Bar', 2000, 'mining', False), ('Gold Fishing Rod', 3, 'tool', True)]), 
    'Sizable Fish Pouch': ('bag', True, [('Bloach', 6750, 'fish', False), ('Average Fish Pouch', 5, 'bag', True)]),
    'Platinet': ('tool', True, [('Fruitfly', 8000, 'bug', False), ('Platinum Ore', 6000, 'mining', False), ('Gilded Net', 3, 'tool', True)]),
    'Sizable Bug Pouch': ('bag', True, [('Fruitfly', 6750, 'bug', False), ('Average Bug Pouch', 5, 'bag', True)]),
    'Sizable Food Pouch': ('bag', True, [('Golden Meat Pie', 9, 'food', False), ('Average Food Pouch', 5, 'bag', True)]),
    'Sizable Materials Pouch': ('bag', True, [('Glass Shard', 15, 'material', False), ('Average Material Pouch', 5, 'bag', True)]),
    'Anvil Tab 3': ('misc', False, [('Platinum Bar', 2000, 'mining', False), ('Not Yet', 2000, '', False), ('Fruitfly', 2000, 'bug', False), ('High Steaks', 1500, 'material', False)]),
    'Empty Box': ('misc', False, [('Hermit Can', 250, 'fish', False), ('Megalodon Tooth', 400, 'material', False), ('Distilled Water', 4, 'material', False)]),
    'FMJ Bullet': ('food', True, [('Gold Ore', 15, 'mining', False), ('Bullet', 2, 'food', True)]),
    'Viking Cap': ('armor', True, [('Militia Helm', 5, 'armor', True), ('Gold Bar', 400, 'mining', False), ('Glass Shard', 2, 'material', False)]),
    'Sleek Coif': ('armor', True, [('Thief Hood', 5, 'armor', True), ('Tropilogs', 2000, 'choppin', False), ('Glass Shard', 2, 'material', False)]),
    'Witch Hat': ('armor', True, [('Top Hat', 5, 'armor', True), ('Corn Kernels', 4000, 'material', False), ('Glass Shard', 2, 'material', False)]),
    'Studded Hide': ('armor', True, [('Hide Shirt', 4, 'armor', True), ('Megalodon Tooth', 4000, 'material', False), ('Nuget Cake', 1, 'material', False)]),
    'Feral Leathering': ('armor', True, [('Fur Shirt', 4, 'armor', True), ('Stick', 3000, 'material', False), ('Nuget Cake', 1, 'material', False)]),
    'Furled Robes': ('armor', True, [('Tattered Cloth', 4, 'armor', False), ('Leather Hide', 1500, 'material', False), ('Nuget Cake', 1, 'material', False)]), 
    'Cavern Trekkers': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Copper Ore', 1500, 'mining', False), ('Iron Ore', 1200, 'mining', False)]),
    'Angler Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Goldfish', 1250, 'fish', False), ('Hermit Can', 1000, 'fish', False)]),
    'Logger Heels': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Jungle Logs', 1600, 'choppin', False), ('Forest Fibres', 1000, 'choppin', False)]),
    'Bandito Boots': ('armor', True, [('Gold Boots', 1, 'armor', True), ('Distilled Water', 9, 'material', False), ('Fly', 2000, 'bug', False), ('Butterfly', 1250, 'bug', False)]),
    'Slurpin Herm': ('food', True, [('Hermit Can', 5, 'fish', False), ('Average Strength Potion', 2, 'food', False)]),
    'Buttered Toasted Butter': ('food', True, [('Butterfly', 5, 'bug', False), ('Kebab Sticks', 1, 'food', False)]),
    'Sandy Satchel': ('bag', True, [('Golden Plop', 1, 'material', False), ('Snakeskinventory Bag', 1, 'bag', False), ('Pocket Sand', 777, 'material', False)])
}


MATERIALS = {
    "World 1": {
        "Anvil": ['Thread', 'Trusty Nails', 'Boring Brick', 'Chain Link', 'Leather Hide'],
        "Boss": ['Amarok Slab', 'Chaotic Amarok Slab'],
        "Chopping": ['Oak Logs', 'Grass Leaf', 'Bleach Logs', 'Jungle Logs', 'Forest Fibres', 'Potty Rolls'],
        "Foods": ['Nomwich', 'Hot Dog', 'Golden Meat Pie'],
        "Mining": ['Crude Oil', 'Copper Ore', 'Copper Bar', 'Iron Ore', 'Iron Bar', 'Gold Ore', 'Gold Bar', 'Platinum Ore', 'Platinum Bar'],
        "Monster Drops": ['Spore Cap', 'Frog Leg', 'Bean Slices', 'Slime Sludge', 'Carrot Cube', 'Red Spore Cap', 'Goblin Ear', 'Plank', 'Bullfrog Horn', 'Stick', 'Corn Kernels'],
        "Other": ['Crimson String', 'Cue Tape', 'Tattered Cloth'],
        "Potions": ['Small Life Potion', 'Small Mana Potion', 'Average Strength Potion'],
        "Unique Drops": ['Spore Tee', 'Dank Paypay Chest', 'Snakeskinventory Bag', 'Woodular Circle', 'Golden Plop']
    },
    "World 2": {
        "Catching": ['Fly', 'Butterfly', 'Sentient Cereal', 'Fruitfly'],
        "Chopping": ['Tropilogs'],
        "Fishing": ['Goldfish', 'Hermit Can', 'Jellyfish', 'Bloach'],
        "Foods": ['Kebab Sticks', 'Meat Pie'],
        "Monster Drops": ['Pocket Sand', 'Megalodon Tooth', 'Crabby Cakey', 'Pincer Arm', 'Potato Remains'],
        "Other": ['Golden Dubloon', 'Distilled Water'],
        "Unique Drops": ['Glass Shard', 'Nuget Cake']
    }
}


MATERIAL_WEIGHTS = [
    ('Thread', 'Oak Logs', 'Nomwich', 'Hot Dog', 'Crude Oil', 'Copper Ore', 'Spore Cap', 'Frog Leg', 'Crimson String', 'Cue Tape'),
    ('Trusty Nails', 'Bleach Logs', 'Copper Bar', 'Iron Ore', 'Bean Slices', 'Slime Sludge', 'Small Life Potion', 'Small Mana Potion', 'Grass Leaf'),
    ('Boring Brick', 'Jungle Logs', 'Iron Bar', 'Carrot Cube', 'Goblin Ear', 'Red Spore Cap', 'Average Strength Potion', 'Spore Tee', 'Dank Paypay Chest', 'Fly', 'Kebab Sticks', 'Meat Pie'),
    ('Chain Link', 'Forest Fibres', 'Gold Ore', 'Plank', 'Tattered Cloth', 'Snakeskinventory Bag', 'Butterfly', 'Goldfish', 'Pocket Sand', 'Golden Dubloon'),
    ('Leather Hide', 'Golden Meat Pie', 'Bullfrog Horn', 'Gold Bar', 'Sentient Cereal', 'Tropilogs', 'Hermit Can', 'Megalodon Tooth'),
    ('Amarok Slab', 'Stick', 'Corn Kernels', 'Jellyfish', 'Crabby Cakey'),
    ('Platinum Ore', 'Fruitfly', 'Bloach', 'Potato Remains', 'Distilled Water', 'Potty Rolls'),
    ('Platinum Bar', 'Pincer Arm', 'Glass Shard'),
    ('Woodular Circle', 'Golden Plop', 'Nuget Cake'),
    ('Chaotic Amarok Slab')
]