RECOMMENDED = [
  { "tier": 0, "items": 0,
    "recipes": [],
    "materials": {},
    "caps": [],
    "format": { "slots": 16, "material": 10, "mining": 10, "fish": 10, "food": 10, "choppin": 10, "bug": 10 }
  },
  { "tier": 1, "items": 3,
    "recipes": ["Boxing Gloves", "Wooden Spear", "Wooden Bow"],
    "materials": ['1 Crimson String', '5 Cue Tape', '50 Spore Cap', '10 Copper Bar', '30 Thread'],
    "caps": [
      { "slots": 16, "material": 10, "mining": 10, "fish": 10, "food": 10, "choppin": 10, "bug": 10 }
    ]
  },
  { "tier": 2, "items": 8,
    "recipes": ["Boxing Gloves", "Wooden Spear", "Wooden Bow", "Gnarled Wand", "Farmer Brim",
                "Orange Tee", "Torn Jeans", "Flip Flops"],
    "materials": ['1 Crimson String', '5 Cue Tape', '120 Spore Cap', '60 Copper Bar', '50 Thread',
                  '55 Oak Logs', '20 Copper Ore', '30 Frog Leg', '50 Bean Slices', '50 Grass Leaf'],
    "caps": [
      {'slots': 16, 'material': 50, 'mining': 50, 'fish': 10, 'food': 10, 'choppin': 50, 'bug': 10},
      {'slots': 19, 'material': 30, 'mining': 30, 'fish': 10, 'food': 10, 'choppin': 30, 'bug': 10},
      {'slots': 23, 'material': 25, 'mining': 25, 'fish': 10, 'food': 10, 'choppin': 25, 'bug': 10},
      {'slots': 27, 'material': 20, 'mining': 20, 'fish': 10, 'food': 10, 'choppin': 20, 'bug': 10},
      {'slots': 32, 'material': 17, 'mining': 17, 'fish': 10, 'food': 10, 'choppin': 17, 'bug': 10},
      {'slots': 35, 'material': 15, 'mining': 15, 'fish': 10, 'food': 10, 'choppin': 15, 'bug': 10},
      {'slots': 43, 'material': 12, 'mining': 12, 'fish': 10, 'food': 10, 'choppin': 12, 'bug': 10},
      {'slots': 47, 'material': 10, 'mining': 10, 'fish': 10, 'food': 10, 'choppin': 10, 'bug': 10}
    ]
  },
  { "tier": 3, "items": 14,
    "recipes": ["Boxing Gloves", "Wooden Spear", "Wooden Bow", "Gnarled Wand",
                "Farmer Brim", "Orange Tee", "Torn Jeans", "Flip Flops",
                "Copper Pickaxe", "Cramped Mining Pouch", "Copper Chopper",
                "Cramped Choppin Pouch", "Leather Cap", "The Stingers"],
    "materials": ['1 Crimson String', '5 Cue Tape', '120 Spore Cap', '130 Copper Bar', '105 Thread',
                  '460 Oak Logs', '170 Copper Ore', '105 Frog Leg', '50 Bean Slices', '50 Grass Leaf',
                  '90 Trusty Nails'],
    "caps": [
      {'slots': 18, 'material': 100, 'mining': 100, 'fish': 10, 'food': 10, 'choppin': 500, 'bug': 10},
      {'slots': 19, 'material': 100, 'mining': 100, 'fish': 10, 'food': 10, 'choppin': 250, 'bug': 10},
      {'slots': 20, 'material': 100, 'mining': 100, 'fish': 10, 'food': 10, 'choppin': 200, 'bug': 10},
      {'slots': 21, 'material': 87, 'mining': 87, 'fish': 10, 'food': 10, 'choppin': 175, 'bug': 10},
      {'slots': 22, 'material': 75, 'mining': 75, 'fish': 10, 'food': 10, 'choppin': 150, 'bug': 10},
      {'slots': 24, 'material': 62, 'mining': 62, 'fish': 10, 'food': 10, 'choppin': 125, 'bug': 10},
      {'slots': 27, 'material': 62, 'mining': 62, 'fish': 10, 'food': 10, 'choppin': 62, 'bug': 10},
      {'slots': 33, 'material': 50, 'mining': 50, 'fish': 10, 'food': 10, 'choppin': 50, 'bug': 10},
      {'slots': 43, 'material': 35, 'mining': 35, 'fish': 10, 'food': 10, 'choppin': 35, 'bug': 10},
      {'slots': 48, 'material': 32, 'mining': 32, 'fish': 10, 'food': 10, 'choppin': 32, 'bug': 10},
      {'slots': 49, 'material': 30, 'mining': 30, 'fish': 10, 'food': 10, 'choppin': 30, 'bug': 10},
      {'slots': 54, 'material': 27, 'mining': 27, 'fish': 10, 'food': 10, 'choppin': 27, 'bug': 10},
      {'slots': 58, 'material': 25, 'mining': 25, 'fish': 10, 'food': 10, 'choppin': 25, 'bug': 10}
    ]
  },
  { "tier": 4, "items": 24,
    "recipes": ['Boxing Gloves', 'Icing Ironbite', 'Saucy Logfries',
                'Eco Friendly Oil', 'Peanut', 'Bullet', 'Slurpin Herm',
                'Buttered Toasted Butter', 'Farmer Brim', 'Wooden Spear',
                'Chaotic Amarok Pendant', 'Wooden Bow', 'FMJ Bullet',
                'Torn Jeans', 'Gnarled Wand', 'Orange Tee', 'Copper Pickaxe',
                'Copper Chopper', 'Leather Cap', 'Cramped Mining Pouch',
                'Cramped Material Pouch', 'Copper Helmet', 'Cramped Fish Pouch',
                'Cramped Bug Pouch'],
    "materials": ['30 Forest Fibers', '210 Fly', '1 Crimson String', '5 Cue Tape', '5 Iron Ore',
                  '2 Small Mana Potion', '6 Jungle Logs', '3 Small Life Potion', '1 Crude Oil',
                  '1 Grass Leaf', '2 Hot Dog', '171 Copper Ore', '1 Bleach Logs', '5 Hermit Can',
                  '2 Average Strength Potion', '5 Butterfly', '1 Kebab Sticks', '120 Spore Cap',
                  '135 Copper Bar', '4 Chaotic Amarok Slab', '10 Amarok Slab', '25 Distilled Water',
                  '105 Thread', '15 Gold Ore', '2 Bullet', '155 Frog Leg', '160 Oak Logs',
                  '125 Trusty Nails', '125 Bean Slices', '180 Goldfish'],
    "caps": [
      {'slots': 33, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 200, 'bug': 200},
      {'slots': 35, 'material': 175, 'mining': 175, 'fish': 175, 'food': 175, 'choppin': 175, 'bug': 175},
      {'slots': 36, 'material': 162, 'mining': 162, 'fish': 162, 'food': 162, 'choppin': 162, 'bug': 162},
      {'slots': 38, 'material': 137, 'mining': 137, 'fish': 137, 'food': 137, 'choppin': 137, 'bug': 137},
      {'slots': 39, 'material': 125, 'mining': 125, 'fish': 125, 'food': 125, 'choppin': 125, 'bug': 125},
      {'slots': 42, 'material': 112, 'mining': 112, 'fish': 112, 'food': 112, 'choppin': 112, 'bug': 112},
      {'slots': 43, 'material': 100, 'mining': 100, 'fish': 100, 'food': 100, 'choppin': 100, 'bug': 100},
      {'slots': 45, 'material': 87, 'mining': 87, 'fish': 87, 'food': 87, 'choppin': 87, 'bug': 87},
      {'slots': 48, 'material': 75, 'mining': 75, 'fish': 75, 'food': 75, 'choppin': 75, 'bug': 75},
      {'slots': 52, 'material': 62, 'mining': 62, 'fish': 62, 'food': 62, 'choppin': 62, 'bug': 62},
      {'slots': 58, 'material': 50, 'mining': 50, 'fish': 50, 'food': 50, 'choppin': 50, 'bug': 50}
    ]
  },
  { "tier": 5, "items": 34,
    "recipes": ['Boxing Gloves', 'Icing Ironbite', 'Saucy Logfries', 'Eco Friendly Oil', 'Peanut', 
                'Bullet', 'Slurpin Herm', 'Buttered Toasted Butter', 'Farmer Brim', 'Wooden Spear',
                'Chaotic Amarok Pendant', 'Wooden Bow', 'FMJ Bullet', 'Torn Jeans', 'Gnarled Wand',
                'Orange Tee', 'Copper Pickaxe', 'Copper Chopper', 'Leather Cap', 'Cramped Mining Pouch',
                'Cramped Material Pouch', 'Copper Helmet', 'Cramped Fish Pouch', 'Cramped Bug Pouch',
                'Copper Boots', 'Flip Flops', 'Cramped Food Pouch', 'The Stingers', 'Copper Platebody',
                'Cramped Choppin Pouch', 'Purple Tupacband', 'Steel Axe', 'Purple Tee',
                'Copper Platelegs'],
    "materials": ['30 Forest Fibers', '210 Fly', '1 Crimson String', '5 Cue Tape', '5 Iron Ore',
                  '2 Small Mana Potion', '6 Jungle Logs', '3 Small Life Potion', '1 Crude Oil',
                  '1 Grass Leaf', '2 Hot Dog', '171 Copper Ore', '1 Bleach Logs', '5 Hermit Can',
                  '2 Average Strength Potion', '5 Butterfly', '1 Kebab Sticks', '120 Spore Cap',
                  '135 Copper Bar', '4 Chaotic Amarok Slab', '10 Amarok Slab', '25 Distilled Water',
                  '105 Thread', '15 Gold Ore', '2 Bullet', '155 Frog Leg', '160 Oak Logs',
                  '125 Trusty Nails', '125 Bean Slices', '180 Goldfish'],
    "caps": [
      {'slots': 47, 'material': 500, 'mining': 500, 'fish': 500, 'food': 500, 'choppin': 500, 'bug': 500},
      {'slots': 48, 'material': 250, 'mining': 500, 'fish': 500, 'food': 500, 'choppin': 500, 'bug': 500},
      {'slots': 49, 'material': 250, 'mining': 250, 'fish': 250, 'food': 250, 'choppin': 500, 'bug': 500},
      {'slots': 50, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 500, 'bug': 500},
      {'slots': 51, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 500, 'bug': 500},
      {'slots': 52, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 200, 'bug': 200},
      {'slots': 53, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 200, 'bug': 200},
      {'slots': 54, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 200, 'bug': 200},
      {'slots': 55, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 200, 'bug': 200},
      {'slots': 56, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 200, 'bug': 200},
      {'slots': 57, 'material': 200, 'mining': 200, 'fish': 200, 'food': 200, 'choppin': 200, 'bug': 200},
      {'slots': 58, 'material': 175, 'mining': 175, 'fish': 175, 'food': 175, 'choppin': 175, 'bug': 175},
      {'slots': 59, 'material': 162, 'mining': 162, 'fish': 162, 'food': 162, 'choppin': 162, 'bug': 162},
      {'slots': 60, 'material': 162, 'mining': 162, 'fish': 162, 'food': 162, 'choppin': 162, 'bug': 162},
      {'slots': 61, 'material': 162, 'mining': 162, 'fish': 162, 'food': 162, 'choppin': 162, 'bug': 162},
      {'slots': 62, 'material': 150, 'mining': 150, 'fish': 150, 'food': 150, 'choppin': 150, 'bug': 150},
      {'slots': 63, 'material': 150, 'mining': 150, 'fish': 150, 'food': 150, 'choppin': 150, 'bug': 150}
    ]
  },
  { "tier": 6, "items": 45,
    "recipes": ['Boxing Gloves', 'Icing Ironbite', 'Saucy Logfries', 'Eco Friendly Oil', 'Peanut',
                'Bullet', 'Slurpin Herm', 'Buttered Toasted Butter', 'Farmer Brim', 'Wooden Spear',
                'Chaotic Amarok Pendant', 'Wooden Bow', 'FMJ Bullet', 'Torn Jeans', 'Gnarled Wand',
                'Orange Tee', 'Copper Pickaxe', 'Copper Chopper', 'Leather Cap', 'Cramped Mining Pouch',
                'Cramped Material Pouch', 'Copper Helmet', 'Cramped Fish Pouch', 'Cramped Bug Pouch',
                'Copper Boots', 'Flip Flops', 'Cramped Food Pouch', 'The Stingers', 'Copper Platebody',
                'Cramped Choppin Pouch', 'Purple Tupacband', 'Steel Axe', 'Purple Tee', 'Copper Platelegs',
                'Blunderbag', 'Blue Tee', 'Green Tee', 'Steel Band', 'Quarterstaff', 'Iron Pickaxe',
                'Small Fish Pouch', 'Small Bug Pouch', 'Small Mining Pouch', 'Small Choppin Pouch',
                'Copper Band'],
    "materials": ['30 Forest Fibers', '210 Fly', '640 Spore Cap', '810 Oak Logs', '1 Crimson String',
                  '5 Cue Tape', '930 Iron Ore', '2 Small Mana Potion', '6 Jungle Logs', '3 Small Life Potion',
                  '101 Crude Oil', '51 Grass Leaf', '27 Hot Dog', '171 Copper Ore', '1301 Bleach Logs',
                  '430 Hermit Can', '2 Average Strength Potion', '430 Butterfly', '1 Kebab Sticks',
                  '1800 Copper Bar', '4 Chaotic Amarok Slab', '10 Amarok Slab', '29 Distilled Water',
                  '255 Thread', '15 Gold Ore', '2 Bullet', '155 Frog Leg', '365 Trusty Nails',
                  '175 Bean Slices', '180 Goldfish', '75 Nomwich', '600 Slime Sludge', '200 Boring Brick',
                  '40 Red Spore Cap', '9 Orange Tee', '5 Spore Tee', '1 Dank Paypay Chest', '775 Iron Bar',
                  '300 Carrot Cube'],
    "caps": []
  },
  { "tier": 7, "items": 55,
    "recipes": ['Boxing Gloves', 'Icing Ironbite', 'Saucy Logfries', 'Eco Friendly Oil',
                'Peanut', 'Bullet', 'Slurpin Herm', 'Buttered Toasted Butter', 'Farmer Brim',
                'Wooden Spear', 'Chaotic Amarok Pendant', 'Wooden Bow', 'FMJ Bullet',
                'Torn Jeans', 'Gnarled Wand', 'Orange Tee', 'Copper Pickaxe', 'Copper Chopper',
                'Leather Cap', 'Cramped Mining Pouch', 'Cramped Material Pouch', 'Copper Helmet',
                'Cramped Fish Pouch', 'Cramped Bug Pouch', 'Copper Boots', 'Flip Flops',
                'Cramped Food Pouch', 'The Stingers', 'Copper Platebody', 'Cramped Choppin Pouch',
                'Purple Tupacband', 'Steel Axe', 'Purple Tee', 'Copper Platelegs', 'Blunderbag',
                'Blue Tee', 'Green Tee', 'Steel Band', 'Quarterstaff', 'Iron Pickaxe',
                'Small Fish Pouch', 'Small Bug Pouch', 'Small Mining Pouch', 'Small Choppin Pouch',
                'Copper Band', 'Iron Platelegs', 'Copper Fish Rod', 'Iron Helmet', 'Iron Hatchet',
                'Birch Longbow', 'Militia Helm', 'Thief Hood', 'Sandy Satchel',
                'Dirty Coal Miner Baggy Soot Pants', 'Copper Netted Net'],
    "materials": ['30 Forest Fibers', '610 Fly', '640 Spore Cap', '810 Oak Logs', '2380 Copper Bar',
                  '475 Bean Slices', '395 Frog Leg', '715 Thread', '1 Crimson String', '5 Cue Tape',
                  '1180 Iron Ore', '2 Small Mana Potion', '956 Jungle Logs', '3 Small Life Potion',
                  '101 Crude Oil', '51 Grass Leaf', '27 Hot Dog', '471 Copper Ore', '1701 Bleach Logs',
                  '430 Hermit Can', '2 Average Strength Potion', '430 Butterfly', '1 Kebab Sticks',
                  '4 Chaotic Amarok Slab', '10 Amarok Slab', '29 Distilled Water', '15 Gold Ore',
                  '2 Bullet', '365 Trusty Nails', '580 Goldfish', '75 Nomwich', '900 Slime Sludge',
                  '750 Boring Brick', '40 Red Spore Cap', '9 Orange Tee', '5 Spore Tee',
                  '1 Dank Paypay Chest', '1370 Iron Bar', '300 Carrot Cube', '400 Goblin Ear',
                  '4 Copper Helmet', '1 Golden Plop', '1 Snakeskinventory Bag', '777 Pocket Sand',
                  '8 Torn Jeans'],
    "caps": []
  },
  { "tier": 8, "items": 70,
    "recipes": ['Boxing Gloves', 'Icing Ironbite', 'Saucy Logfries', 'Eco Friendly Oil',
                'Peanut', 'Bullet', 'Slurpin Herm', 'Buttered Toasted Butter', 'Farmer Brim',
                'Wooden Spear', 'Chaotic Amarok Pendant', 'Wooden Bow', 'FMJ Bullet', 'Torn Jeans',
                'Gnarled Wand', 'Orange Tee', 'Copper Pickaxe', 'Copper Chopper', 'Leather Cap',
                'Cramped Mining Pouch', 'Cramped Material Pouch', 'Copper Helmet',
                'Cramped Fish Pouch', 'Cramped Bug Pouch', 'Copper Boots', 'Flip Flops',
                'Cramped Food Pouch', 'The Stingers', 'Copper Platebody', 'Cramped Choppin Pouch',
                'Purple Tupacband', 'Steel Axe', 'Purple Tee', 'Copper Platelegs', 'Blunderbag',
                'Blue Tee', 'Green Tee', 'Steel Band', 'Quarterstaff', 'Iron Pickaxe', 'Small Fish Pouch',
                'Small Bug Pouch', 'Small Mining Pouch', 'Small Choppin Pouch', 'Copper Band',
                'Iron Platelegs', 'Copper Fish Rod', 'Iron Helmet', 'Iron Hatchet', 'Birch Longbow',
                'Militia Helm', 'Thief Hood', 'Sandy Satchel', 'Dirty Coal Miner Baggy Soot Pants',
                'Copper Netted Net', 'Fur Shirt', 'Iron Platebody', 'Sleek Shank', 'Iron Boots',
                'Amarok Hinds', 'Top Hat', 'Furled Robes', 'Iron Fishing Rod', 'Reinforced Net',
                'Amarok Bodyplate', 'Amarok Paws', 'Hide Shirt', 'Average Material Pouch',
                'Bleached Designer Wode Patch Pants', 'Gold Boots'],
    "materials": ['30 Forest Fibers', '610 Fly', '865 Spore Cap', '1450 Oak Logs', '4440 Copper Bar',
                  '1125 Bean Slices', '1195 Frog Leg', '1305 Thread', '3915 Trusty Nails', '3480 Iron Bar',
                  '8 Copper Boots', '1200 Slime Sludge', '950 Boring Brick', '1 Crimson String', '5 Cue Tape',
                  '1180 Iron Ore', '2 Small Mana Potion', '1756 Jungle Logs', '3 Small Life Potion',
                  '101 Crude Oil', '301 Grass Leaf', '27 Hot Dog', '471 Copper Ore', '2926 Bleach Logs',
                  '1280 Hermit Can', '2 Average Strength Potion', '1280 Butterfly', '1 Kebab Sticks',
                  '4 Chaotic Amarok Slab', '31 Amarok Slab', '43 Distilled Water', '15 Gold Ore', '2 Bullet',
                  '580 Goldfish', '75 Nomwich', '40 Red Spore Cap', '9 Orange Tee', '5 Spore Tee',
                  '1 Dank Paypay Chest', '300 Carrot Cube', '900 Goblin Ear', '6 Copper Helmet',
                  '1 Golden Plop', '1 Snakeskinventory Bag', '777 Pocket Sand', '18 Torn Jeans',
                  '3 Wooden Spear', '3 Wooden Bow', '3 Gnarled Wand', '1750 Chain Link', '1000 Bullfrog Horn',
                  '4 Tattered Cloth', '1500 Leather Hide', '1 Nuget Cake', '800 Forest Fibres',
                  '1200 Corn Kernels', '3 Iron Boots', '2 Copper Platebody', '1 Steel Axe',
                  '10 Cramped Material Pouch', '1 Glass Shard', '400 Plank', '400 Gold Bar'],
    "caps": []
  },
  { "tier": 9, "items": 90,
    "recipes": ['Boxing Gloves', 'Icing Ironbite', 'Saucy Logfries', 'Eco Friendly Oil', 'Peanut',
                'Bullet', 'Slurpin Herm', 'Buttered Toasted Butter', 'Farmer Brim', 'Wooden Spear',
                'Chaotic Amarok Pendant', 'Wooden Bow', 'FMJ Bullet', 'Torn Jeans', 'Gnarled Wand',
                'Orange Tee', 'Copper Pickaxe', 'Copper Chopper', 'Leather Cap', 'Cramped Mining Pouch',
                'Cramped Material Pouch', 'Copper Helmet', 'Cramped Fish Pouch', 'Cramped Bug Pouch',
                'Copper Boots', 'Flip Flops', 'Cramped Food Pouch', 'The Stingers', 'Copper Platebody',
                'Cramped Choppin Pouch', 'Purple Tupacband', 'Steel Axe', 'Purple Tee', 'Copper Platelegs',
                'Blunderbag', 'Blue Tee', 'Green Tee', 'Steel Band', 'Quarterstaff', 'Iron Pickaxe',
                'Small Fish Pouch', 'Small Bug Pouch', 'Small Mining Pouch', 'Small Choppin Pouch',
                'Copper Band', 'Iron Platelegs', 'Copper Fish Rod', 'Iron Helmet', 'Iron Hatchet',
                'Birch Longbow', 'Militia Helm', 'Thief Hood', 'Sandy Satchel',
                'Dirty Coal Miner Baggy Soot Pants', 'Copper Netted Net', 'Fur Shirt', 'Iron Platebody',
                'Sleek Shank', 'Iron Boots', 'Amarok Hinds', 'Top Hat', 'Furled Robes', 'Iron Fishing Rod',
                'Reinforced Net', 'Amarok Bodyplate', 'Amarok Paws', 'Hide Shirt', 'Average Material Pouch',
                'Bleached Designer Wode Patch Pants', 'Gold Boots', 'Starlight', 'Dooble Goopi',
                'Goo Galoshes', 'Royal Bayonet', 'Black Tee', 'Strung Bludgeon', 'Gold Platebody',
                'Spiked Menace', 'Amarok Helmet', 'Viking Cap', 'Gold Platelegs', 'Gold Helmet',
                'Average Mining Pouch', 'Cavern Trekkers', 'Average Fish Pouch', 'Average Bug Pouch',
                'Angler Boots', 'Logger Heels', 'Sleek Coif', 'Feral Leathering'],
    "materials": ['30 Forest Fibers', '4410 Fly', '1975 Spore Cap', '2400 Oak Logs', '11675 Copper Bar',
                  '2925 Bean Slices', '1195 Frog Leg', '3255 Thread', '7665 Trusty Nails', '7180 Iron Bar',
                  '22 Copper Boots', '5500 Slime Sludge', '1550 Boring Brick', '41 Orange Tee',
                  '160 Red Spore Cap', '5626 Bleach Logs', '11 Spore Tee', '4971 Copper Ore', '30 Copper Helmet',
                  '5780 Iron Ore', '4675 Gold Bar', '9 Iron Boots', '158 Distilled Water', '4130 Goldfish',
                  '5905 Hermit Can', '5005 Butterfly', '2900 Goblin Ear', '1 Crimson String', '5 Cue Tape',
                  '2 Small Mana Potion', '4356 Jungle Logs', '3 Small Life Potion', '101 Crude Oil',
                  '301 Grass Leaf', '27 Hot Dog', '2 Average Strength Potion', '1 Kebab Sticks',
                  '4 Chaotic Amarok Slab', '51 Amarok Slab', '15 Gold Ore', '2 Bullet', '75 Nomwich',
                  '1 Dank Paypay Chest', '300 Carrot Cube', '1 Golden Plop', '1 Snakeskinventory Bag',
                  '2277 Pocket Sand', '18 Torn Jeans', '3 Wooden Spear', '3 Wooden Bow', '3 Gnarled Wand',
                  '2750 Chain Link', '10000 Bullfrog Horn', '4 Tattered Cloth', '1500 Leather Hide',
                  '2 Nuget Cake', '6050 Forest Fibres', '1200 Corn Kernels', '7 Copper Platebody',
                  '4 Steel Axe', '10 Cramped Material Pouch', '15 Glass Shard', '400 Plank', '3 Quarterstaff',
                  '1 Copper Band', '1 Steel Band', '3 Blue Tee', '3 Purple Tee', '3 Green Tee',
                  '3 Birch Longbow', '8 Woodular Circle', '5 Militia Helm', '6 Copper Platelegs',
                  '10 Cramped Mining Pouch', '4 Small Mining Pouch', '3 Gold Boots', '10 Cramped Fish Pouch',
                  '5 Small Fish Pouch', '10 Cramped Bug Pouch', '5 Small Bug Pouch', '5 Thief Hood',
                  '2000 Tropilogs', '4 Fur Shirt', '3000 Stick'],
    "caps": []
  },
  { "tier": 10, "items": 110,
    "recipes": ['Boxing Gloves', 'Icing Ironbite', 'Saucy Logfries', 'Eco Friendly Oil', 'Peanut', 
                'Bullet', 'Slurpin Herm', 'Buttered Toasted Butter', 'Farmer Brim', 'Wooden Spear',
                'Chaotic Amarok Pendant', 'Wooden Bow', 'FMJ Bullet', 'Torn Jeans', 'Gnarled Wand',
                'Orange Tee', 'Copper Pickaxe', 'Copper Chopper', 'Leather Cap', 'Cramped Mining Pouch',
                'Cramped Material Pouch', 'Copper Helmet', 'Cramped Fish Pouch', 'Cramped Bug Pouch',
                'Copper Boots', 'Flip Flops', 'Cramped Food Pouch', 'The Stingers', 'Copper Platebody',
                'Cramped Choppin Pouch', 'Purple Tupacband', 'Steel Axe', 'Purple Tee', 'Copper Platelegs',
                'Blunderbag', 'Blue Tee', 'Green Tee', 'Steel Band', 'Quarterstaff', 'Iron Pickaxe',
                'Small Fish Pouch', 'Small Bug Pouch', 'Small Mining Pouch', 'Small Choppin Pouch',
                'Copper Band', 'Iron Platelegs', 'Copper Fish Rod', 'Iron Helmet', 'Iron Hatchet',
                'Birch Longbow', 'Militia Helm', 'Thief Hood', 'Sandy Satchel',
                'Dirty Coal Miner Baggy Soot Pants', 'Copper Netted Net', 'Fur Shirt', 'Iron Platebody',
                'Sleek Shank', 'Iron Boots', 'Amarok Hinds', 'Top Hat', 'Furled Robes', 'Iron Fishing Rod',
                'Reinforced Net', 'Amarok Bodyplate', 'Amarok Paws', 'Hide Shirt', 'Average Material Pouch',
                'Bleached Designer Wode Patch Pants', 'Gold Boots', 'Starlight', 'Dooble Goopi',
                'Goo Galoshes', 'Royal Bayonet', 'Black Tee', 'Strung Bludgeon', 'Gold Platebody',
                'Spiked Menace', 'Amarok Helmet', 'Viking Cap', 'Gold Platelegs', 'Gold Helmet',
                'Average Mining Pouch', 'Cavern Trekkers', 'Average Fish Pouch', 'Average Bug Pouch',
                'Angler Boots', 'Logger Heels', 'Sleek Coif', 'Feral Leathering', 'Platinum Shins',
                'Golden Axe', 'Bandito Boots', 'Gold Pickaxe', 'Average Choppin Pouch', 'Platinum Helmet',
                'Defenders Dignity', 'Witch Hat', 'Bandage Wraps', 'Platinum Boots', 'Sizable Materials Pouch',
                'Gold Fishing Rod', 'Platinum Platbody', 'Studded Hide', 'Average Food Pouch', 'Gilded Net',
                'Enforced Slasher', 'Crows Nest', 'Sizable Mining Pouch', 'Pharoah Bow'],
    "materials": ['30 Forest Fibers', '6410 Fly', '1975 Spore Cap', '8900 Oak Logs', '16020 Copper Bar',
                  '6175 Bean Slices', '3695 Frog Leg', '3255 Thread', '17015 Trusty Nails', '14055 Iron Bar',
                  '26 Copper Boots', '14800 Slime Sludge', '7200 Boring Brick', '41 Orange Tee', '160 Red Spore Cap',
                  '14776 Bleach Logs', '11 Spore Tee', '12471 Copper Ore', '40 Copper Helmet', '25780 Iron Ore',
                  '13075 Gold Bar', '11 Iron Boots', '292 Distilled Water', '20130 Goldfish', '12655 Hermit Can',
                  '13005 Butterfly', '4500 Goblin Ear', '14206 Jungle Logs', '1800 Carrot Cube', '60 Cramped Material Pouch',
                  '37 Glass Shard', '12000 Chain Link', '15 Copper Platebody', '17 Steel Axe', '825 Nomwich', '277 Hot Dog',
                  '1202 Small Mana Potion', '1803 Small Life Potion', '15600 Forest Fibres', '12 Quarterstaff',
                  '60 Cramped Mining Pouch', '24 Small Mining Pouch', '12 Birch Longbow', '1 Crimson String', '5005 Cue Tape',
                  '101 Crude Oil', '301 Grass Leaf', '2 Average Strength Potion', '1 Kebab Sticks', '4 Chaotic Amarok Slab',
                  '51 Amarok Slab', '15 Gold Ore', '2 Bullet', '1 Dank Paypay Chest', '28 Golden Plop',
                  '1 Snakeskinventory Bag', '2277 Pocket Sand', '18 Torn Jeans', '3 Wooden Spear', '3 Wooden Bow',
                  '3 Gnarled Wand', '10000 Bullfrog Horn', '4 Tattered Cloth', '14500 Leather Hide', '13 Nuget Cake',
                  '5200 Corn Kernels', '400 Plank', '1 Copper Band', '1 Steel Band', '3 Blue Tee', '3 Purple Tee',
                  '3 Green Tee', '18 Woodular Circle', '5 Militia Helm', '6 Copper Platelegs', '4 Gold Boots',
                  '10 Cramped Fish Pouch', '5 Small Fish Pouch', '10 Cramped Bug Pouch', '5 Small Bug Pouch', '5 Thief Hood',
                  '9500 Tropilogs', '4 Fur Shirt', '3000 Stick', '500 Sentient Cereal', '6 Iron Platelegs',
                  '3000 Platinum Bar', '10 Golden Dubloon', '2000 Crabby Cakey', '5 Iron Hatchet', '6500 Megalodon Tooth',
                  '5 Iron Pickaxe', '10 Cramped Choppin Pouch', '5 Small Choppin Pouch', '14000 Jellyfish', '4 Iron Helmet',
                  '5 Top Hat', '10 The Stingers', '2000 Potty Rolls', '5 Average Material Pouch', '5 Iron Fishing Rod',
                  '5000 Potato Remains', '5 Iron Platebody', '4 Hide Shirt', '10 Cramped Food Pouch', '250 Meat Pie',
                  '600 Icing Ironbite', '600 Saucy Logfries', '5 Reinforced Net', '3 Royal Bayonet', '10000 Fruitfly',
                  '3 Starlight', '6750 Platinum Ore', '5 Average Mining Pouch', '10000 Bloach', '3 Spiked Menace'],
    "caps": []
  }
]
